import { useCallback, useEffect, useMemo, useState } from 'react'
import { CircleMarker, MapContainer, Popup, TileLayer, useMap, useMapEvents } from 'react-leaflet'
import 'leaflet/dist/leaflet.css'
import { Navigate, NavLink, Route, Routes, useLocation, useNavigate, useParams, useSearchParams } from 'react-router-dom'
import { QRCodeSVG } from 'qrcode.react'
import { api } from './api'
import type { GeocodedLocation } from './api'
import type { AdminCategory, AdminDashboard, AdminProviderDetail, AdminService, AdminSlot, AdminUser, Booking, BookingConfirmation, Category, DealSlot, MyProviderProfile, Notification, PortalRole, ProviderProfile, ProviderResource, ProviderService, ProviderSlot, ProviderVenue, Report, Session } from './types'
import './App.css'

const sessionKey = 'openslot-session'
const formatMoney = (value: number) => new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND', maximumFractionDigits: 0 }).format(value)
const formatTime = (value: string) => new Intl.DateTimeFormat('vi-VN', { timeZone: 'Asia/Ho_Chi_Minh', weekday: 'short', day: '2-digit', month: '2-digit', hour: '2-digit', minute: '2-digit' }).format(new Date(value))
const formatSlotWindow = (startAtUtc: string, endAtUtc: string) => `${formatTime(startAtUtc)} – ${new Intl.DateTimeFormat('vi-VN', { timeZone: 'Asia/Ho_Chi_Minh', hour: '2-digit', minute: '2-digit' }).format(new Date(endAtUtc))}`
const hasRole = (session: Session | null, role: string) => session?.user.roles.includes(role) ?? false
const portalRoles: PortalRole[] = ['Customer', 'Provider', 'Manager', 'Admin']
const portalLabel = (role: PortalRole) => ({ Customer: 'Khách hàng', Provider: 'Đối tác', Manager: 'Quản lý vận hành', Admin: 'Quản trị viên' })[role]
const roleLabel = (roles: string[]) => roles.includes('Admin') ? 'Quản trị viên' : roles.includes('Manager') ? 'Quản lý vận hành' : roles.includes('Provider') ? 'Đối tác' : 'Khách hàng'
const defaultPortalRole = (roles: string[]): PortalRole => roles.includes('Admin') ? 'Admin' : roles.includes('Manager') ? 'Manager' : roles.includes('Provider') ? 'Provider' : 'Customer'
const activePortalRole = (session: Session | null): PortalRole => session?.activeRole && session.user.roles.includes(session.activeRole) ? session.activeRole : defaultPortalRole(session?.user.roles ?? ['Customer'])
const homeFor = (session: Session | null) => ({ Customer: '/', Provider: '/provider', Manager: '/manager', Admin: '/admin' })[activePortalRole(session)]
const isPortalRole = (value: string | null): value is PortalRole => portalRoles.includes(value as PortalRole)
const vietnamLocations = ['Hà Nội', 'Hải Phòng', 'Huế', 'Đà Nẵng', 'Cần Thơ', 'Thành phố Hồ Chí Minh', 'Lai Châu', 'Điện Biên', 'Sơn La', 'Lào Cai', 'Tuyên Quang', 'Cao Bằng', 'Thái Nguyên', 'Lạng Sơn', 'Quảng Ninh', 'Bắc Ninh', 'Phú Thọ', 'Ninh Bình', 'Hưng Yên', 'Thanh Hóa', 'Nghệ An', 'Hà Tĩnh', 'Quảng Trị', 'Quảng Ngãi', 'Gia Lai', 'Khánh Hòa', 'Lâm Đồng', 'Đắk Lắk', 'Đồng Nai', 'Tây Ninh', 'Vĩnh Long', 'Đồng Tháp', 'Cà Mau', 'An Giang']
const popularServiceSearches = ['Sân cầu lông', 'Sân pickleball', 'Gội đầu dưỡng sinh', 'Làm móng nhanh', 'Bàn làm việc', 'Phòng họp nhóm', 'Studio chụp ảnh', 'Phòng podcast', 'Bàn bi-a', 'Phòng karaoke mini', 'Rửa xe máy', 'Máy giặt tự phục vụ']
const priceSuggestions = ['49000', '79000', '99000', '120000', '150000', '180000', '200000', '250000', '300000', '500000']
const capacitySuggestions = ['1', '2', '4', '6', '8', '10', '20']
const venueNameSuggestions = ['Sân cầu lông ABC', 'Salon Minh Anh', 'Coffee Study', 'Campus Court', 'Glow Studio', 'Focus Hub']
const addressSuggestions = ['Trần Duy Hưng, Hà Nội', 'Nguyễn Chí Thanh, Hà Nội', 'Cầu Giấy, Hà Nội', 'Đống Đa, Hà Nội', 'Hai Bà Trưng, Hà Nội']
const descriptionSuggestions = ['Ưu đãi cho khung giờ còn trống trong ngày', 'Không gian sạch sẽ, đầy đủ tiện nghi', 'Phù hợp cho khách đặt lịch sát giờ']
const normalizePhone = (value: string) => value.replace(/\D/g, '').slice(0, 10)
const isValidPhone = (value: string) => /^0\d{9}$/.test(value)
const normalizeSearch = (value: string) => value.normalize('NFD').replace(/\p{Diacritic}/gu, '').toLocaleLowerCase('vi-VN').trim()
const filterSuggestions = (items: string[], query: string, limit = 8) => {
  const normalizedQuery = normalizeSearch(query)
  if (!normalizedQuery) return []
  return [...new Set(items)].filter((item) => normalizeSearch(item).startsWith(normalizedQuery)).slice(0, limit)
}

function getStoredSession(): Session | null { try { return JSON.parse(localStorage.getItem(sessionKey) ?? 'null') as Session | null } catch { return null } }

function App() {
  const [session, setSession] = useState<Session | null>(getStoredSession)
  const saveSession = (next: Session | null) => { const normalized = next ? { ...next, activeRole: activePortalRole(next) } : null; setSession(normalized); if (normalized) localStorage.setItem(sessionKey, JSON.stringify(normalized)); else localStorage.removeItem(sessionKey) }
  const switchPortal = (role: PortalRole) => { if (session?.user.roles.includes(role)) saveSession({ ...session, activeRole: role }) }
  const activeRole = activePortalRole(session); const isProvider = hasRole(session, 'Provider')
  return <>
    <header className="site-header">
      <NavLink to="/" className="brand"><span className="brand-mark"><i className="bi bi-lightning-charge-fill" /></span>Open<span>Slot</span></NavLink>
      <nav className="main-nav">{!session ? <NavLink to="/" end>Khám phá</NavLink> : <>{activeRole === 'Customer' && <><NavLink to="/" end>Khám phá</NavLink><NavLink to="/bookings">Lịch của tôi</NavLink>{isProvider ? <NavLink to="/provider" onClick={() => switchPortal('Provider')}>Khu vực đối tác</NavLink> : <NavLink to="/provider-application">Đăng ký cửa hàng</NavLink>}</>}{activeRole === 'Provider' && <><NavLink to="/" onClick={() => switchPortal('Customer')}>Khám phá & đặt chỗ</NavLink><NavLink to="/provider">Quản lý cửa hàng</NavLink></>}{activeRole === 'Manager' && <NavLink to="/manager">Vận hành nền tảng</NavLink>}{activeRole === 'Admin' && <NavLink to="/admin">Quản trị hệ thống</NavLink>}</>}</nav>
      <div className="user-actions">{session ? <><NavLink to="/notifications" className="notification-link" aria-label="Thông báo"><i className="bi bi-bell" /></NavLink><span className="user-label"><b>{session.user.displayName}</b><small>{portalLabel(activeRole)}</small></span><button className="btn btn-link text-decoration-none" onClick={() => saveSession(null)}>Đăng xuất</button></> : <><NavLink className="btn btn-link text-decoration-none" to="/login">Đăng nhập</NavLink><NavLink className="btn btn-primary rounded-pill px-4" to="/register">Tạo tài khoản</NavLink></>}</div>
    </header>
    <main><Routes>
      <Route path="/" element={activeRole === 'Customer' ? <ExplorePage /> : <Navigate to={homeFor(session)} replace />} />
      <Route path="/slots/:slotId" element={<SlotDetailPage session={session} />} />
      <Route path="/login" element={<LoginEntryPage onAuthenticated={saveSession} />} />
      <Route path="/register" element={<AuthPage mode="register" onAuthenticated={saveSession} />} />
      <Route path="/bookings" element={hasRole(session, 'Customer') ? <BookingsPage session={session!} /> : <Navigate to={session ? homeFor(session) : '/login'} replace />} />
      <Route path="/provider-application" element={hasRole(session, 'Customer') ? <ProviderApplicationPage session={session!} onAuthenticated={saveSession} /> : <Navigate to={session ? homeFor(session) : '/login'} replace />} />
      <Route path="/provider" element={session?.user.roles.includes('Provider') ? <ProviderPage session={session} /> : <Navigate to="/" replace />} />
      <Route path="/manager" element={session?.user.roles.includes('Manager') ? <AdminPage session={session} mode="manager" /> : <Navigate to={homeFor(session)} replace />} />
      <Route path="/admin" element={session?.user.roles.includes('Admin') ? <AdminPage session={session} mode="admin" /> : <Navigate to={homeFor(session)} replace />} />
      <Route path="/notifications" element={session ? <NotificationsPage session={session} /> : <Navigate to="/login" replace />} />
      <Route path="*" element={<NotFoundPage />} />
    </Routes></main>
    <footer><div><b>OpenSlot</b><span>Săn thời điểm trống. Tận hưởng giá hợp lý.</span></div><small>Demo đồ án cá nhân · ASP.NET Core + React</small></footer>
  </>
}

function ExplorePage() {
  const [categories, setCategories] = useState<Category[]>([]); const [slots, setSlots] = useState<DealSlot[]>([])
  const [activeCategory, setActiveCategory] = useState(''); const [locationQuery, setLocationQuery] = useState(''); const [keyword, setKeyword] = useState(''); const [appliedKeyword, setAppliedKeyword] = useState(''); const [appliedLocation, setAppliedLocation] = useState<{ label: string; district?: string; latitude?: number; longitude?: number } | null>(null); const [loading, setLoading] = useState(true); const [locating, setLocating] = useState(false); const [hasSearched, setHasSearched] = useState(false); const [error, setError] = useState(''); const [mapMode, setMapMode] = useState(false)
  useEffect(() => { api.categories().then(setCategories).catch(() => setCategories([])) }, [])
  // oxlint-disable-next-line react/set-state-in-effect -- loading is part of this request lifecycle
  useEffect(() => { setLoading(true); setError(''); const params = new URLSearchParams(); if (activeCategory) params.set('category', activeCategory); if (appliedLocation?.district) params.set('district', appliedLocation.district); if (appliedKeyword) params.set('q', appliedKeyword); if (appliedLocation?.latitude != null && appliedLocation.longitude != null) { params.set('latitude', String(appliedLocation.latitude)); params.set('longitude', String(appliedLocation.longitude)) }; const query = params.toString() ? `?${params}` : ''; api.slots(query).then(setSlots).catch((e: Error) => setError(e.message)).finally(() => setLoading(false)) }, [activeCategory, appliedKeyword, appliedLocation])
  const useMyLocation = () => { if (!navigator.geolocation) { setError('Trình duyệt không hỗ trợ định vị.'); return }; setLocating(true); navigator.geolocation.getCurrentPosition((position) => { const location = { label: 'Vị trí hiện tại của bạn', latitude: position.coords.latitude, longitude: position.coords.longitude }; setLocationQuery('Vị trí hiện tại'); setAppliedLocation(location); setHasSearched(true); setError(''); setLocating(false) }, () => { setError('Không thể lấy vị trí. Hãy cho phép quyền vị trí trong trình duyệt.'); setLocating(false) }) }
  const search = async (event: React.FormEvent) => { event.preventDefault(); setError(''); setHasSearched(true); setAppliedKeyword(keyword.trim()); const requestedLocation = locationQuery.trim(); if (!requestedLocation) { setAppliedLocation(null); return }; setLocating(true); try { const location = await api.geocodeLocation(requestedLocation); setAppliedLocation(location ?? { label: requestedLocation, district: requestedLocation }); if (!location) setError(`Không xác định được “${requestedLocation}” trên bản đồ; đang tìm theo tên khu vực.`) } catch { setAppliedLocation({ label: requestedLocation, district: requestedLocation }); setError('Dịch vụ bản đồ đang bận; OpenSlot đã chuyển sang tìm theo tên khu vực.') } finally { setLocating(false) } }
  const recommendationSlots = slots.slice(0, 6)
  const locationSuggestions = useMemo(() => filterSuggestions(vietnamLocations, locationQuery), [locationQuery])
  const serviceSuggestions = useMemo(() => filterSuggestions([...popularServiceSearches, ...categories.map((item) => item.name), ...slots.flatMap((slot) => [slot.serviceName, slot.venueName])], keyword), [categories, keyword, slots])
  return <div className="explore-page">
    <section className="hero-section"><div className="container"><p className="eyebrow"><i className="bi bi-stars" /> Ưu đãi sát giờ, có giới hạn</p><h1>Chỗ trống hôm nay,<br /><em>giá tốt ngay lúc này.</em></h1><p className="hero-copy">OpenSlot kết nối các khung giờ còn trống từ đối tác với người dùng sẵn sàng trải nghiệm. Không chờ sale dài ngày, chỉ chọn đúng thời điểm.</p><form className="search-box" onSubmit={search}><div><i className="bi bi-search" /><input aria-label="Tìm dịch vụ" list="service-search-suggestions" autoComplete="off" value={keyword} onChange={(e) => setKeyword(e.target.value)} placeholder="Tìm sân, salon, chỗ ngồi..." /><datalist id="service-search-suggestions">{serviceSuggestions.map((suggestion) => <option value={suggestion} key={suggestion} />)}</datalist></div><div><i className="bi bi-geo-alt" /><input aria-label="Khu vực" list="location-search-suggestions" autoComplete="off" value={locationQuery} onChange={(e) => setLocationQuery(e.target.value)} placeholder="Địa điểm, ví dụ: Hà Nội" /><datalist id="location-search-suggestions">{locationSuggestions.map((suggestion) => <option value={suggestion} key={suggestion} />)}</datalist></div><button type="button" className={`location-button ${appliedLocation?.latitude != null ? 'active' : ''}`} onClick={useMyLocation} title="Dùng vị trí hiện tại" aria-label="Dùng vị trí hiện tại"><i className={`bi bi-${locating ? 'hourglass-split' : 'crosshair'}`} /></button><button disabled={locating} className="btn btn-primary rounded-pill">{locating ? 'Đang xác định...' : 'Khám phá ngay'} <i className="bi bi-arrow-right" /></button></form></div></section>
    <section className="container content-section">{hasSearched && <NearbyResults slots={recommendationSlots} location={appliedLocation} loading={loading || locating} />}<div className="category-row"><button className={!activeCategory ? 'category active' : 'category'} onClick={() => setActiveCategory('')}><i className="bi bi-grid" />Tất cả</button>{categories.map((item) => <button key={item.id} className={activeCategory === item.slug ? 'category active' : 'category'} onClick={() => setActiveCategory(item.slug)}><i className={`bi ${item.icon || 'bi-tag'}`} />{item.name}</button>)}</div><div className="section-heading"><div><p className="eyebrow">Sắp diễn ra</p><h2>Slot đáng săn gần bạn</h2></div><button className="view-toggle" onClick={() => setMapMode(!mapMode)}><i className={`bi bi-${mapMode ? 'list-ul' : 'map'}`} /> {mapMode ? 'Xem danh sách' : 'Xem trên bản đồ'}</button></div>{error && <div className="alert alert-warning">{error}</div>}{loading ? <div className="empty-state"><div className="spinner-border text-primary" /><p>Đang tìm slot tốt nhất...</p></div> : mapMode ? <SlotMap slots={slots} location={appliedLocation} /> : <SlotGrid slots={slots} />}</section>
    <section className="how-it-works"><div className="container"><p className="eyebrow">Đơn giản, minh bạch</p><h2>Săn slot trong 3 bước</h2><div className="steps"><Step icon="bi-search-heart" number="01" title="Tìm đúng lúc" text="Lọc dịch vụ, địa điểm và giờ phù hợp với lịch của bạn." /><Step icon="bi-ticket-perforated" number="02" title="Giữ chỗ nhanh" text="Xác nhận slot trước khi hết chỗ; giá và điều kiện luôn rõ ràng." /><Step icon="bi-qr-code-scan" number="03" title="Check-in gọn" text="Dùng mã QR hoặc PIN tại địa điểm để bắt đầu trải nghiệm." /></div></div></section>
  </div>
}

function Step({ icon, number, title, text }: { icon: string; number: string; title: string; text: string }) { return <article className="step"><span>{number}</span><i className={`bi ${icon}`} /><h3>{title}</h3><p>{text}</p></article> }
function SlotGrid({ slots }: { slots: DealSlot[] }) { return <div className="slot-grid">{slots.length ? slots.map((slot) => <SlotCard key={slot.id} slot={slot} />) : <div className="empty-state full"><i className="bi bi-calendar-x" /><h3>Chưa có slot phù hợp</h3><p>Thử đổi danh mục hoặc khu vực tìm kiếm nhé.</p></div>}</div> }
function SlotCard({ slot }: { slot: DealSlot }) { const discount = Math.round((1 - slot.dealPriceVnd / slot.originalPriceVnd) * 100); return <NavLink to={`/slots/${slot.id}`} state={{ slot }} className="slot-card"><div className={`slot-visual visual-${slot.categorySlug}`}><span className="discount">-{discount}%</span><span className="spot-label"><i className="bi bi-lightning-fill" /> Còn {slot.remainingCapacity} chỗ</span><i className="bi bi-clock-history visual-icon" /></div><div className="slot-body"><div className="slot-meta"><span>{slot.categoryName}</span><span><i className="bi bi-geo-alt" /> {slot.distanceKm == null ? slot.district : `${slot.distanceKm} km`}</span></div><h3>{slot.serviceName}</h3><p className="venue"><i className="bi bi-building" /> {slot.venueName}{slot.resourceName && <> · <i className="bi bi-pin-map" /> {slot.resourceName}{slot.resourceCode ? ` (${slot.resourceCode})` : ''}</>}</p><div className="time-row"><i className="bi bi-calendar-event" /> {formatSlotWindow(slot.startAtUtc, slot.endAtUtc)}</div><div className="price-row"><div><del>{formatMoney(slot.originalPriceVnd)}</del><strong>{formatMoney(slot.dealPriceVnd)}</strong></div><span className="arrow-circle"><i className="bi bi-arrow-up-right" /></span></div></div></NavLink> }

function NearbyResults({ slots, location, loading }: { slots: DealSlot[]; location: { label: string; latitude?: number; longitude?: number } | null; loading: boolean }) {
  return <section className="nearby-results" aria-live="polite"><div className="nearby-heading"><div><p className="eyebrow">Gợi ý quanh khu vực</p><h2>{location?.label ?? 'Các địa điểm phù hợp'}</h2></div>{!loading && <span><i className="bi bi-geo-alt-fill" /> {slots.length} lựa chọn gần nhất</span>}</div>{loading ? <div className="nearby-loading"><div className="spinner-border text-primary" /><p>Đang tìm địa điểm và ưu đãi phù hợp...</p></div> : slots.length ? <><SlotMap slots={slots} location={location} compact /><div className="nearby-strip">{slots.slice(0, 3).map((slot) => <NavLink key={slot.id} to={`/slots/${slot.id}`} state={{ slot }}><b>{slot.serviceName}</b><span>{slot.venueName} · {slot.distanceKm == null ? slot.district : `${slot.distanceKm} km`}</span><strong>{formatMoney(slot.dealPriceVnd)}</strong></NavLink>)}</div></> : <div className="nearby-empty"><i className="bi bi-map" /><div><b>Chưa có dịch vụ khả dụng quanh khu vực này</b><span>Thử một địa điểm lân cận hoặc bỏ trống ô địa điểm để xem tất cả.</span></div></div>}</section>
}

function FitMapBounds({ points }: { points: [number, number][] }) {
  const map = useMap()
  useEffect(() => { if (points.length === 1) map.setView(points[0], 13); else if (points.length > 1) map.fitBounds(points, { padding: [28, 28], maxZoom: 14 }) }, [map, points])
  return null
}

function SlotMap({ slots, location, compact = false }: { slots: DealSlot[]; location?: { latitude?: number; longitude?: number } | null; compact?: boolean }) {
  const userPoint = useMemo<[number, number] | null>(() => location?.latitude != null && location.longitude != null ? [location.latitude, location.longitude] : null, [location])
  const points = useMemo<[number, number][]>(() => [...(userPoint ? [userPoint] : []), ...slots.map((slot) => [slot.latitude, slot.longitude] as [number, number])], [slots, userPoint])
  const center = points[0] ?? [21.0285, 105.8542]
  return <div className={`map-canvas ${compact ? 'compact' : ''}`}><MapContainer key={`${center[0]}-${center[1]}-${slots.map((slot) => slot.id).join('-')}`} center={center} zoom={13} scrollWheelZoom className="leaflet-map"><TileLayer attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" /><FitMapBounds points={points} />{userPoint && <CircleMarker center={userPoint} radius={9} pathOptions={{ color: '#ffffff', weight: 3, fillColor: '#2f6fed', fillOpacity: 1 }}><Popup>Vị trí bạn đã tìm</Popup></CircleMarker>}{slots.map((slot) => <CircleMarker key={slot.id} center={[slot.latitude, slot.longitude]} radius={11} pathOptions={{ color: '#ffffff', weight: 3, fillColor: '#ee7158', fillOpacity: 1 }}><Popup><div className="map-info"><b>{slot.serviceName}</b><span>{slot.venueName}{slot.resourceName ? ` · ${slot.resourceName}` : ''} · {formatMoney(slot.dealPriceVnd)}</span><NavLink to={`/slots/${slot.id}`} state={{ slot }}>Xem ưu đãi</NavLink></div></Popup></CircleMarker>)}</MapContainer></div>
}

function SlotDetailPage({ session }: { session: Session | null }) {
  const { slotId } = useParams(); const navigate = useNavigate(); const location = useLocation(); const locationSlot = (location.state as { slot?: DealSlot } | null)?.slot; const [slot, setSlot] = useState<DealSlot | null>(locationSlot ?? null); const [status, setStatus] = useState<'idle' | 'loading'>('idle'); const [error, setError] = useState(''); const [confirmation, setConfirmation] = useState<BookingConfirmation | null>(null)
  const canBook = hasRole(session, 'Customer')
  useEffect(() => { if (!slotId || slot) return; api.slot(slotId).then(setSlot).catch((e: Error) => setError(e.message)) }, [slotId, slot])
  if (!slot) return <div className="container detail-shell"><div className="empty-state"><p>{error || 'Đang tải thông tin slot...'}</p></div></div>
  const book = async () => { if (!session) { navigate('/login'); return }; if (!canBook) return; setStatus('loading'); setError(''); try { setConfirmation(await api.book(slot.id, session.accessToken)) } catch (e) { setError(e instanceof Error ? e.message : 'Không thể giữ chỗ.') } finally { setStatus('idle') } }
  const report = async () => { if (!session) { navigate('/login'); return }; const reason = window.prompt('Mô tả vấn đề bạn muốn báo cáo (tối thiểu 10 ký tự):'); if (!reason) return; try { await api.createReport('slot', slot.id, reason, session.accessToken); window.alert('Cảm ơn bạn. Báo cáo đã được gửi tới quản trị viên.') } catch (e) { setError(e instanceof Error ? e.message : 'Không thể gửi báo cáo.') } }
  if (confirmation) return <div className="container confirmation-page"><div className="confirmation-card"><span className="success-mark"><i className="bi bi-check-lg" /></span><p className="eyebrow">Giữ chỗ thành công</p><h1>Hẹn gặp bạn tại<br />{slot.venueName}!</h1><p>Đưa QR hoặc PIN bên dưới khi check-in. Bạn có thể xem lại trong “Lịch của tôi”.</p><div className="qr-wrap"><QRCodeSVG value={confirmation.qrPayload} size={180} /><strong>{confirmation.publicCode}</strong><span>PIN check-in: <b>{confirmation.checkInPin}</b></span></div><NavLink to="/bookings" className="btn btn-primary rounded-pill px-4">Xem lịch của tôi</NavLink></div></div>
  return <div className="container detail-shell"><NavLink to="/" className="back-link"><i className="bi bi-arrow-left" /> Quay lại khám phá</NavLink><div className="detail-grid"><section className="detail-main"><div className={`detail-visual visual-${slot.categorySlug}`}><span className="discount">-{Math.round((1 - slot.dealPriceVnd / slot.originalPriceVnd) * 100)}%</span><i className="bi bi-lightning-charge-fill" /></div><p className="eyebrow mt-4">{slot.categoryName}</p><h1>{slot.serviceName}</h1><p className="detail-venue"><i className="bi bi-building" /> {slot.venueName} · {slot.district}, {slot.city}</p><div className="detail-facts"><Fact icon="bi-calendar-event" label="Bắt đầu" value={formatTime(slot.startAtUtc)} /><Fact icon="bi-clock" label="Kết thúc" value={formatTime(slot.endAtUtc)} /><Fact icon="bi-geo-alt" label="Địa điểm" value={`${slot.district}, ${slot.city}`} />{slot.resourceName && <Fact icon="bi-pin-map" label="Đơn vị đã đặt" value={`${slot.resourceName}${slot.resourceCode ? ` · ${slot.resourceCode}` : ''}${slot.resourceLocation ? ` · ${slot.resourceLocation}` : ''}`} />}</div><article className="info-box"><h3><i className="bi bi-shield-check" /> Chính sách OpenSlot</h3><p>Giữ chỗ chỉ hợp lệ trước giờ bắt đầu ít nhất 15 phút. Hủy sát giờ hoặc không đến có thể được tính strike để bảo vệ đối tác và cộng đồng.</p></article><button onClick={report} className="report-button"><i className="bi bi-flag" /> Báo cáo thông tin không chính xác</button></section><aside className="booking-panel"><p>Giá ưu đãi sát giờ</p><div className="detail-price"><del>{formatMoney(slot.originalPriceVnd)}</del><strong>{formatMoney(slot.dealPriceVnd)}</strong></div><div className="seat-note"><i className="bi bi-people" /> Còn <b>{slot.remainingCapacity}/{slot.capacity}</b> chỗ khả dụng</div>{error && <div className="alert alert-danger py-2 small">{error}</div>}<button disabled={status === 'loading' || !slot.remainingCapacity || (!!session && !canBook)} onClick={book} className="btn btn-primary w-100 rounded-pill py-3">{status === 'loading' ? 'Đang giữ chỗ...' : !session ? 'Đăng nhập để giữ chỗ' : canBook ? 'Giữ chỗ ngay' : 'Chỉ tài khoản khách hàng được đặt'} <i className="bi bi-arrow-right" /></button><small className="d-block text-center mt-3">Không thanh toán online trong bản demo.</small></aside></div></div>
}
function Fact({ icon, label, value }: { icon: string; label: string; value: string }) { return <div><i className={`bi ${icon}`} /><span><small>{label}</small><b>{value}</b></span></div> }

function LoginEntryPage({ onAuthenticated }: { onAuthenticated: (session: Session) => void }) {
  const [searchParams] = useSearchParams()
  const portal = searchParams.get('role')
  if (!isPortalRole(portal)) return <LoginPortalSelectionPage />
  return <AuthPage mode="login" portal={portal} onAuthenticated={onAuthenticated} />
}

function LoginPortalSelectionPage() {
  const portals: Array<{ role: PortalRole; icon: string; title: string; text: string }> = [
    { role: 'Customer', icon: 'bi-bag-heart', title: 'Khách hàng', text: 'Khám phá ưu đãi, giữ chỗ và quản lý lịch trải nghiệm.' },
    { role: 'Provider', icon: 'bi-shop', title: 'Đối tác', text: 'Quản lý cửa hàng, địa điểm, dịch vụ và slot còn trống.' },
    { role: 'Manager', icon: 'bi-clipboard-data', title: 'Manager', text: 'Duyệt đối tác và theo dõi vận hành nền tảng.' },
    { role: 'Admin', icon: 'bi-shield-lock', title: 'Admin', text: 'Quản trị hệ thống, phân quyền và kiểm soát dữ liệu.' }
  ]
  return <div className="portal-page"><section className="portal-intro"><NavLink to="/" className="brand"><span className="brand-mark"><i className="bi bi-lightning-charge-fill" /></span>Open<span>Slot</span></NavLink><div><p className="eyebrow">Chọn khu vực sử dụng</p><h1>Một tài khoản,<br />nhiều nhu cầu.</h1><p>Nếu vừa là chủ cửa hàng vừa là khách hàng, bạn có thể chuyển cổng sử dụng bất cứ lúc nào sau khi đăng nhập.</p></div></section><section className="portal-options"><div className="portal-options-inner"><p className="eyebrow">Đăng nhập OpenSlot</p><h1>Bạn muốn vào với vai trò nào?</h1><p className="portal-copy">Chọn đúng khu vực trước khi nhập email và mật khẩu.</p><div className="portal-grid">{portals.map((item) => <NavLink className="portal-card" key={item.role} to={`/login?role=${item.role}`}><i className={`bi ${item.icon}`} /><span><b>{item.title}</b><small>{item.text}</small></span><i className="bi bi-arrow-right-short" /></NavLink>)}</div><p className="switch-auth">Chưa có tài khoản khách hàng? <NavLink to="/register">Tạo tài khoản miễn phí</NavLink></p></div></section></div>
}

function AuthPage({ mode, portal, onAuthenticated }: { mode: 'login' | 'register'; portal?: PortalRole; onAuthenticated: (session: Session) => void }) {
  const navigate = useNavigate(); const [displayName, setDisplayName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false)
  const submit = async (event: React.FormEvent) => {
    event.preventDefault()
    setError('')
    if (mode === 'register' && !/(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,}/.test(password)) {
      setError('Mật khẩu cần tối thiểu 8 ký tự, gồm chữ hoa, chữ thường và số.')
      return
    }
    setLoading(true)
    try {
      const next = mode === 'login' ? await api.login(email, password) : await api.register(displayName, email, password)
      if (portal && !next.user.roles.includes(portal)) {
        throw new Error(`Tài khoản này chưa có quyền ${portalLabel(portal)}. Hãy chọn đúng khu vực đăng nhập.`)
      }
      const session = { ...next, activeRole: portal ?? 'Customer' }
      onAuthenticated(session)
      navigate(homeFor(session))
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Không thể tiếp tục.')
    } finally {
      setLoading(false)
    }
  }
  const demoAccount = portal === 'Provider' ? 'provider@openslot.local / Provider@12345' : portal === 'Manager' ? 'manager@openslot.local / Manager@12345' : portal === 'Admin' ? 'admin@openslot.local / Admin@12345' : 'customer@openslot.local / Customer@12345'
  return <div className="auth-page"><section className="auth-pitch"><NavLink to="/" className="brand"><span className="brand-mark"><i className="bi bi-lightning-charge-fill" /></span>Open<span>Slot</span></NavLink><div><p className="eyebrow">{portal ? `Cổng ${portalLabel(portal)}` : 'Tận hưởng thông minh'}</p><h1>{portal === 'Provider' ? <>Quản lý cửa hàng<br />gọn trong một nơi.</> : portal === 'Manager' || portal === 'Admin' ? <>Vận hành rõ ràng,<br />quyền hạn minh bạch.</> : <>Khoảnh khắc trống<br />cũng đáng giá.</>}</h1><p>{portal === 'Provider' ? 'Tài khoản đối tác vẫn có thể chuyển sang cổng Khách hàng để đặt dịch vụ.' : 'Chọn dịch vụ đúng nơi, đúng thời điểm, đúng ngân sách.'}</p></div><div className="quote"><i className="bi bi-quote" /> Đừng để một khung giờ tốt bị bỏ trống.</div></section><section className="auth-form-wrap"><form onSubmit={submit} className="auth-form">{mode === 'login' && <NavLink className="auth-back" to="/login"><i className="bi bi-arrow-left" /> Chọn khu vực khác</NavLink>}<p className="eyebrow">{mode === 'login' ? `Đăng nhập ${portal ? portalLabel(portal) : 'OpenSlot'}` : 'Tạo tài khoản miễn phí'}</p><h1>{mode === 'login' ? 'Chào mừng trở lại' : 'Bắt đầu săn slot'}</h1>{mode === 'register' && <label>Họ và tên<input required value={displayName} onChange={(e) => setDisplayName(e.target.value)} placeholder="Nguyễn Văn A" /></label>}<label>Email<input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="ban@email.com" /></label><label>Mật khẩu<input required minLength={8} type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Tối thiểu 8 ký tự" />{mode === 'register' && <small className="form-hint">Tối thiểu 8 ký tự, có chữ hoa, chữ thường và số.</small>}</label>{error && <div className="alert alert-danger">{error}</div>}<button disabled={loading} className="btn btn-primary rounded-pill py-3">{loading ? 'Đang xử lý...' : mode === 'login' ? `Vào cổng ${portal ? portalLabel(portal) : 'OpenSlot'}` : 'Tạo tài khoản'} <i className="bi bi-arrow-right" /></button><p className="switch-auth">{mode === 'login' ? portal === 'Customer' ? <>Chưa có tài khoản? <NavLink to="/register">Đăng ký</NavLink></> : portal === 'Provider' ? <><b>Muốn đăng ký bán dịch vụ?</b> <NavLink to="/register">Tạo tài khoản Khách hàng</NavLink><span>Sau đó đăng nhập cổng Khách hàng, chọn “Đăng ký cửa hàng” và chờ Manager duyệt.</span></> : <>Cổng này chỉ dành cho tài khoản đã được cấp quyền.</> : <>Đã có tài khoản? <NavLink to="/login">Đăng nhập</NavLink></>}</p>{mode === 'login' && <div className="demo-login"><b>Demo nhanh</b><span>{demoAccount}</span></div>}</form></section></div>
}

function ProviderApplicationPage({ session, onAuthenticated }: { session: Session; onAuthenticated: (session: Session) => void }) {
  const navigate = useNavigate(); const [businessName, setBusinessName] = useState(''); const [contactPhone, setContactPhone] = useState(''); const [description, setDescription] = useState(''); const [error, setError] = useState(''); const [saving, setSaving] = useState(false)
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setError(''); if (!isValidPhone(contactPhone)) { setError('Số điện thoại không hợp lệ, vui lòng nhập lại.'); return }; setSaving(true); try { const next = await api.applyForProvider({ businessName, contactPhone, description }, session.accessToken); onAuthenticated({ ...next, activeRole: 'Provider' }); navigate('/provider') } catch (e) { setError(e instanceof Error ? e.message : 'Không thể gửi hồ sơ đối tác.') } finally { setSaving(false) } }
  return <div className="container application-page"><section className="application-intro"><p className="eyebrow">Dành cho chủ cửa hàng</p><h1>Đưa khung giờ trống của bạn lên OpenSlot</h1><p>Hồ sơ sẽ được Manager kiểm tra trước khi bạn phát hành slot. Sau khi gửi, bạn vẫn có thể hoàn thiện địa điểm, dịch vụ và đơn vị nhận đặt chỗ.</p><div className="application-steps"><span><b>01</b> Gửi hồ sơ cửa hàng</span><span><b>02</b> Manager xét duyệt</span><span><b>03</b> Phát hành slot sát giờ</span></div></section><form className="provider-application-form" onSubmit={submit}><p className="eyebrow">Hồ sơ đối tác</p><h2>Thông tin cửa hàng</h2><label>Tên cửa hàng/doanh nghiệp<input required minLength={2} maxLength={160} value={businessName} onChange={(e) => setBusinessName(e.target.value)} placeholder="Ví dụ: Cà phê Mây" /></label><label>Số điện thoại liên hệ<input required type="tel" inputMode="numeric" autoComplete="tel" minLength={10} maxLength={10} pattern="0[0-9]{9}" title="Gồm đúng 10 chữ số và bắt đầu bằng số 0" value={contactPhone} onChange={(e) => setContactPhone(normalizePhone(e.target.value))} placeholder="0900000000" /><small className="form-hint">Gồm đúng 10 chữ số và bắt đầu bằng số 0.</small></label><label>Mô tả ngắn<input maxLength={2000} value={description} onChange={(e) => setDescription(e.target.value)} placeholder="Bạn cung cấp dịch vụ gì, ở khu vực nào?" /></label>{error && <div className="alert alert-danger">{error}</div>}<button disabled={saving} className="btn btn-primary rounded-pill py-3">{saving ? 'Đang gửi...' : 'Gửi hồ sơ để xét duyệt'} <i className="bi bi-arrow-right" /></button><small>Tài khoản sẽ được bổ sung quyền Đối tác, vẫn giữ quyền Khách hàng để đặt dịch vụ khi cần.</small></form></div>
}

function BookingsPage({ session }: { session: Session }) {
  const [bookings, setBookings] = useState<Booking[]>([]); const [error, setError] = useState(''); const [loading, setLoading] = useState(true)
  // oxlint-disable-next-line react/set-state-in-effect -- loading belongs to the request lifecycle
  const refresh = () => { setLoading(true); api.myBookings(session.accessToken).then(setBookings).catch((e: Error) => setError(e.message)).finally(() => setLoading(false)) }
  useEffect(refresh, [session.accessToken])
  const cancel = async (booking: Booking) => { if (!window.confirm(`Hủy booking ${booking.publicCode}?`)) return; try { await api.cancelBooking(booking.id, 'Người dùng hủy từ giao diện', session.accessToken); refresh() } catch (e) { setError(e instanceof Error ? e.message : 'Không thể hủy booking.') } }
  return <div className="container dashboard"><p className="eyebrow">Tài khoản của bạn</p><h1>Lịch trải nghiệm</h1><p className="dashboard-copy">Mã QR/check-in PIN được mở khi bạn giữ chỗ. Hãy đến đúng giờ để giữ lịch sử tốt.</p>{error && <div className="alert alert-danger">{error}</div>}{loading ? <div className="empty-state"><div className="spinner-border text-primary" /></div> : bookings.length ? <div className="booking-list">{bookings.map((booking) => <article className="booking-item" key={booking.id}><div className="booking-date"><b>{new Intl.DateTimeFormat('vi-VN', { day: '2-digit' }).format(new Date(booking.startAtUtc))}</b><span>thg {new Intl.DateTimeFormat('vi-VN', { month: '2-digit' }).format(new Date(booking.startAtUtc))}</span></div><div className="booking-info"><span className="status-pill">{booking.status === 0 ? 'Đã xác nhận' : booking.status === 3 ? 'Đã hủy' : 'Đã cập nhật'}</span><h3>{booking.serviceName}</h3><p><i className="bi bi-building" /> {booking.venueName}{booking.resourceName ? ` · ${booking.resourceName}${booking.resourceCode ? ` (${booking.resourceCode})` : ''}` : ''} · <i className="bi bi-clock" /> {formatTime(booking.startAtUtc)}</p><b>{formatMoney(booking.dealPriceVnd)}</b></div><div className="booking-actions"><code>{booking.publicCode}</code>{booking.status === 0 && <button onClick={() => cancel(booking)} className="btn btn-outline-danger btn-sm rounded-pill">Hủy chỗ</button>}</div></article>)}</div> : <div className="empty-state"><i className="bi bi-calendar-heart" /><h3>Chưa có lịch nào</h3><NavLink className="btn btn-primary rounded-pill" to="/">Khám phá slot ngay</NavLink></div>}</div>
}

function ProviderPage({ session }: { session: Session }) {
  const [slots, setSlots] = useState<ProviderSlot[]>([]); const [services, setServices] = useState<ProviderService[]>([]); const [resources, setResources] = useState<ProviderResource[]>([]); const [profile, setProfile] = useState<MyProviderProfile | null>(null); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [loading, setLoading] = useState(true); const [showForm, setShowForm] = useState(false)
  // oxlint-disable-next-line react/set-state-in-effect -- loading belongs to the request lifecycle
  const refresh = () => { setLoading(true); Promise.all([api.providerSlots(session.accessToken), api.providerServices(session.accessToken), api.providerResources(session.accessToken), api.providerProfile(session.accessToken)]).then(([slotData, serviceData, resourceData, profileData]) => { setSlots(slotData); setServices(serviceData); setResources(resourceData); setProfile(profileData) }).catch((e: Error) => setError(e.message)).finally(() => setLoading(false)) }
  useEffect(refresh, [session.accessToken])
  const publish = async (id: string) => { if (profile?.status !== 1) { setError('Hồ sơ cửa hàng đang chờ Manager duyệt nên chưa thể phát hành slot.'); return }; try { await api.publishProviderSlot(id, session.accessToken); setNotice('Slot đã được phát hành.'); refresh() } catch (e) { setError(e instanceof Error ? e.message : 'Không thể phát hành slot.') } }
  const resubmit = async () => { try { await api.resubmitProviderProfile(session.accessToken); setNotice('Đã gửi lại hồ sơ để Manager xét duyệt.'); refresh() } catch (e) { setError(e instanceof Error ? e.message : 'Không thể gửi lại hồ sơ.') } }
  const status = profile?.status
  return <div className="container dashboard"><p className="eyebrow">Khu vực đối tác</p><div className="provider-heading"><div><h1>Quản lý cửa hàng và slot trống</h1><p className="dashboard-copy">Mỗi slot phải gắn với một sân, bàn, ghế hoặc phòng cụ thể để không bị trùng lịch.</p></div><button disabled={status === 2} onClick={() => setShowForm(!showForm)} className="btn btn-primary rounded-pill"><i className="bi bi-plus-lg" /> {showForm ? 'Đóng form' : 'Tạo slot'}</button></div>{status === 0 && <div className="provider-approval-banner pending"><i className="bi bi-hourglass-split" /><div><b>Hồ sơ cửa hàng đang chờ Manager duyệt</b><span>Bạn có thể hoàn thiện địa điểm, dịch vụ và slot nháp. Chỉ slot của hồ sơ đã duyệt mới được công khai.</span></div></div>}{status === 3 && <div className="provider-approval-banner rejected"><i className="bi bi-exclamation-diamond" /><div><b>Hồ sơ cần bổ sung trước khi hoạt động</b><span>Hãy rà soát thông tin cửa hàng, sau đó gửi lại để Manager xét duyệt.</span></div><button onClick={resubmit} className="btn btn-sm btn-outline-danger">Gửi lại xét duyệt</button></div>}{status === 2 && <div className="provider-approval-banner suspended"><i className="bi bi-lock" /><div><b>Hồ sơ đối tác đang bị tạm khóa</b><span>Bạn không thể thay đổi dữ liệu hoặc phát hành slot trong thời gian này.</span></div></div>}{showForm && <ProviderSlotForm services={services} resources={resources} token={session.accessToken} onDone={() => { setShowForm(false); setNotice('Đã tạo slot nháp. Hãy phát hành khi hồ sơ được duyệt.'); refresh() }} onError={setError} />}{error && <div className="alert alert-danger">{error}</div>}{notice && <div className="alert alert-success">{notice}</div>}{loading ? <div className="empty-state"><div className="spinner-border text-primary" /></div> : <><div className="provider-table"><div className="table-head"><span>Dịch vụ / đơn vị</span><span>Thời gian</span><span>Giá deal</span><span>Chỗ còn</span></div>{slots.map((slot) => <div className="table-row" key={slot.id}><span><b>{slot.serviceName}</b><small>{slot.venueName} · {slot.resourceName}{slot.resourceCode ? ` (${slot.resourceCode})` : ''}</small></span><span>{formatSlotWindow(slot.startAtUtc, slot.endAtUtc)}</span><span><b>{formatMoney(slot.dealPriceVnd)}</b></span><span>{Math.max(0, slot.capacity - slot.confirmedBookingCount)}/{slot.capacity} {slot.status === 0 && (status === 1 ? <button onClick={() => publish(slot.id)} className="btn btn-sm btn-outline-primary ms-2">Phát hành</button> : <small className="slot-awaiting-approval">Chờ Manager duyệt</small>)}</span></div>)}</div><CheckInPanel token={session.accessToken} /><ProviderCatalogPanel token={session.accessToken} onServicesChanged={refresh} /></>}</div>
}

function ProviderSlotForm({ services, resources, token, onDone, onError }: { services: ProviderService[]; resources: ProviderResource[]; token: string; onDone: () => void; onError: (message: string) => void }) {
  const [serviceId, setServiceId] = useState(''); const [resourceId, setResourceId] = useState(''); const [start, setStart] = useState(''); const [end, setEnd] = useState(''); const [originalPrice, setOriginalPrice] = useState(''); const [dealPrice, setDealPrice] = useState(''); const [capacity, setCapacity] = useState('1'); const [saving, setSaving] = useState(false)
  const selected = services.find((x) => x.id === serviceId); const matchingResources = resources.filter((x) => x.isActive && x.venueId === selected?.venueId); const selectedResource = matchingResources.find((x) => x.id === resourceId)
  const chooseService = (value: string) => { setServiceId(value); setResourceId(''); setCapacity('1') }
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!serviceId || !resourceId || !start || !end) return; const startAt = new Date(start); const endAt = new Date(end); if (endAt <= startAt) { onError('Giờ kết thúc phải sau giờ bắt đầu.'); return }; const closesAt = new Date(startAt.getTime() - 15 * 60000); setSaving(true); try { await api.createProviderSlot({ serviceOfferingId: serviceId, bookableResourceId: resourceId, startAtUtc: startAt.toISOString(), endAtUtc: endAt.toISOString(), bookingOpensAtUtc: new Date().toISOString(), bookingClosesAtUtc: closesAt.toISOString(), originalPriceVnd: Number(originalPrice), dealPriceVnd: Number(dealPrice), capacity: Number(capacity) }, token); onDone() } catch (e) { onError(e instanceof Error ? e.message : 'Không thể tạo slot.') } finally { setSaving(false) } }
  return <form onSubmit={submit} className="provider-form"><h3>Tạo slot nháp</h3><p className="form-hint">Dịch vụ không có thời lượng cố định. Hãy nhập khung giờ trống thực tế của đơn vị để khách biết chính xác thời điểm có thể đặt.</p><label>Dịch vụ<select required value={serviceId} onChange={(e) => chooseService(e.target.value)}><option value="">Chọn dịch vụ</option>{services.map((service) => <option key={service.id} value={service.id}>{service.name} · {service.venueName}</option>)}</select></label><label>Đơn vị nhận đặt chỗ<select required disabled={!selected} value={resourceId} onChange={(e) => setResourceId(e.target.value)}><option value="">{selected ? 'Chọn sân, bàn, ghế hoặc phòng' : 'Chọn dịch vụ trước'}</option>{matchingResources.map((resource) => <option key={resource.id} value={resource.id}>{resource.name}{resource.code ? ` · ${resource.code}` : ''}{resource.floorOrZone ? ` · ${resource.floorOrZone}` : ''}</option>)}</select>{selected && !matchingResources.length && <small className="text-danger">Địa điểm này chưa có đơn vị đặt chỗ. Hãy thêm ở phần thiết lập gian hàng.</small>}</label><label>Giờ bắt đầu<input required type="datetime-local" value={start} onChange={(e) => setStart(e.target.value)} /></label><label>Giờ kết thúc<input required type="datetime-local" min={start || undefined} value={end} onChange={(e) => setEnd(e.target.value)} /></label><label>Giá gốc (VND)<input required min="1" type="number" list="slot-price-suggestions" value={originalPrice} onChange={(e) => setOriginalPrice(e.target.value)} /></label><label>Giá deal (VND)<input required min="1" type="number" list="slot-price-suggestions" value={dealPrice} onChange={(e) => setDealPrice(e.target.value)} /></label><label>Số chỗ<input required min="1" max={selectedResource?.maxCapacity ?? 100} type="number" list="slot-capacity-suggestions" value={capacity} onChange={(e) => setCapacity(e.target.value)} />{selectedResource && <small>Tối đa {selectedResource.maxCapacity} chỗ cho {selectedResource.name}.</small>}</label><datalist id="slot-price-suggestions">{priceSuggestions.map((value) => <option value={value} key={value} />)}</datalist><datalist id="slot-capacity-suggestions">{capacitySuggestions.map((value) => <option value={value} key={value} />)}</datalist><button disabled={saving || !services.length || !resources.length || !resourceId} className="btn btn-primary rounded-pill">{saving ? 'Đang tạo...' : 'Lưu slot nháp'}</button><small>OpenSlot chặn hai slot trùng giờ trên cùng một đơn vị. Slot luôn đóng nhận đặt chỗ trước giờ bắt đầu tối thiểu 15 phút.</small></form>
}

function ProviderCatalogPanel({ token, onServicesChanged }: { token: string; onServicesChanged: () => void }) {
  const [profile, setProfile] = useState<MyProviderProfile | null>(null); const [venues, setVenues] = useState<ProviderVenue[]>([]); const [resources, setResources] = useState<ProviderResource[]>([]); const [categories, setCategories] = useState<Category[]>([]); const [mode, setMode] = useState<'none' | 'profile' | 'venue' | 'resource' | 'service'>('none'); const [message, setMessage] = useState(''); const [error, setError] = useState('')
  const load = useCallback(() => Promise.all([api.providerProfile(token), api.providerVenues(token), api.providerResources(token), api.categories()]).then(([profileData, venueData, resourceData, categoryData]) => { setProfile(profileData); setVenues(venueData); setResources(resourceData); setCategories(categoryData) }).catch((e: Error) => setError(e.message)), [token])
  useEffect(() => { load() }, [load])
  const success = (text: string) => { setMode('none'); setError(''); setMessage(text); load(); onServicesChanged() }
  const deactivate = async (resource: ProviderResource) => { if (!window.confirm(`Ngưng sử dụng ${resource.name}?`)) return; try { await api.deactivateProviderResource(resource.id, token); success(`Đã ngưng sử dụng ${resource.name}.`) } catch (e) { setError(e instanceof Error ? e.message : 'Không thể ngưng đơn vị đặt chỗ.') } }
  const isSuspended = profile?.status === 2
  const providerStatusText = profile?.status === 0 ? 'Chờ duyệt' : profile?.status === 1 ? 'Đã duyệt' : profile?.status === 2 ? 'Tạm khóa' : profile?.status === 3 ? 'Cần bổ sung' : 'Đang tải'
  return <section className="catalog-panel"><div className="admin-section-title"><div><p className="eyebrow">Thiết lập gian hàng</p><h2>Hồ sơ, địa điểm và đơn vị đặt chỗ</h2></div><div className="catalog-actions"><button disabled={isSuspended} onClick={() => setMode('profile')} className="btn btn-sm btn-outline-secondary">Sửa hồ sơ</button><button disabled={isSuspended} onClick={() => setMode('venue')} className="btn btn-sm btn-outline-secondary">Thêm địa điểm</button><button disabled={isSuspended} onClick={() => setMode('resource')} className="btn btn-sm btn-outline-secondary">Thêm đơn vị</button><button disabled={isSuspended} onClick={() => setMode('service')} className="btn btn-sm btn-outline-primary">Thêm dịch vụ</button></div></div>{error && <div className="alert alert-danger mt-3">{error}</div>}{message && <div className="alert alert-success mt-3">{message}</div>}<div className="catalog-summary"><article><small>Đối tác</small><b>{profile?.businessName ?? 'Đang tải...'}</b><span>{profile?.contactPhone}</span></article><article><small>Trạng thái hồ sơ</small><b>{providerStatusText}</b><span>{isSuspended ? 'Tạm dừng thao tác' : 'Manager quản lý xét duyệt'}</span></article><article><small>Địa điểm</small><b>{venues.length}</b><span>{venues.map((x) => x.name).join(', ') || 'Chưa có địa điểm'}</span></article><article><small>Đơn vị có thể đặt</small><b>{resources.filter((x) => x.isActive).length}</b><span>{resources.filter((x) => x.isActive).map((x) => x.name).join(', ') || 'Chưa có đơn vị'}</span></article></div>{resources.length > 0 && <div className="resource-list">{resources.map((resource) => <article key={resource.id} className={!resource.isActive ? 'inactive' : ''}><div><b>{resource.name}{resource.code ? ` · ${resource.code}` : ''}</b><span>{resource.venueName} · {resource.resourceType} · {resource.maxCapacity} chỗ{resource.floorOrZone ? ` · ${resource.floorOrZone}` : ''}{resource.positionDescription ? ` · ${resource.positionDescription}` : ''}</span></div>{resource.isActive ? <button disabled={isSuspended} onClick={() => deactivate(resource)} className="btn btn-sm btn-outline-secondary">Ngưng sử dụng</button> : <small>Đã ngưng</small>}</article>)}</div>}{mode === 'profile' && profile && <ProviderProfileForm profile={profile} token={token} onDone={() => success('Đã cập nhật hồ sơ đối tác.')} onError={setError} />}{mode === 'venue' && <VenueForm token={token} onDone={() => success('Đã thêm địa điểm.')} onError={setError} />}{mode === 'resource' && <ResourceForm token={token} venues={venues} onDone={() => success('Đã thêm đơn vị đặt chỗ.')} onError={setError} />}{mode === 'service' && <ServiceForm token={token} venues={venues} categories={categories} onDone={() => success('Đã thêm dịch vụ.')} onError={setError} />}</section>
}

function ProviderProfileForm({ profile, token, onDone, onError }: { profile: MyProviderProfile; token: string; onDone: () => void; onError: (message: string) => void }) {
  const [businessName, setBusinessName] = useState(profile.businessName); const [contactPhone, setContactPhone] = useState(profile.contactPhone); const [description, setDescription] = useState(profile.description ?? ''); const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!isValidPhone(contactPhone)) { onError('Số điện thoại không hợp lệ, vui lòng nhập lại.'); return }; try { await api.updateProviderProfile({ businessName, contactPhone, description }, token); onDone() } catch (e) { onError(e instanceof Error ? e.message : 'Không thể cập nhật hồ sơ.') } }
  return <form className="provider-form catalog-form" onSubmit={submit}><h3>Sửa hồ sơ đối tác</h3><label>Tên doanh nghiệp<input required name="organization" autoComplete="organization" minLength={2} maxLength={160} value={businessName} onChange={(e) => setBusinessName(e.target.value)} /></label><label>Số điện thoại<input required name="tel" type="tel" autoComplete="tel" inputMode="numeric" minLength={10} maxLength={10} pattern="0[0-9]{9}" title="Gồm đúng 10 chữ số và bắt đầu bằng số 0" value={contactPhone} onChange={(e) => setContactPhone(normalizePhone(e.target.value))} /><small className="form-hint">Gồm đúng 10 chữ số và bắt đầu bằng số 0.</small></label><label>Mô tả<input maxLength={2000} list="profile-description-suggestions" value={description} onChange={(e) => setDescription(e.target.value)} /></label><datalist id="profile-description-suggestions">{descriptionSuggestions.map((value) => <option value={value} key={value} />)}</datalist><button className="btn btn-primary rounded-pill">Lưu hồ sơ</button></form>
}

function VenueForm({ token, onDone, onError }: { token: string; onDone: () => void; onError: (message: string) => void }) {
  const [name, setName] = useState('')
  const [addressLine, setAddressLine] = useState('')
  const [previewLocation, setPreviewLocation] = useState<GeocodedLocation | null>(null)
  const [isMapOpen, setIsMapOpen] = useState(false)
  const [resolving, setResolving] = useState(false)
  const [saving, setSaving] = useState(false)
  const [lookupError, setLookupError] = useState('')
  const resolveAddress = async () => {
    const requestedAddress = addressLine.trim()
    if (requestedAddress.length < 5) { setLookupError('Hãy nhập địa chỉ cụ thể trước khi xem trên bản đồ.'); return null }
    setResolving(true); setLookupError('')
    try {
      const location = await api.geocodeLocation(requestedAddress)
      if (!location) { setPreviewLocation(null); setLookupError('Không tìm thấy địa chỉ. Hãy thêm số nhà, đường/phường và tỉnh thành.'); return null }
      setPreviewLocation(location)
      return location
    } catch {
      setPreviewLocation(null); setLookupError('Dịch vụ bản đồ đang bận. Hãy thử lại sau ít phút.'); return null
    } finally { setResolving(false) }
  }
  const openMap = async () => {
    setIsMapOpen(true)
    if (addressLine.trim()) await resolveAddress()
  }
  const pickLocationFromMap = async (latitude: number, longitude: number) => {
    setResolving(true); setLookupError('')
    setPreviewLocation({ label: 'Đang xác định địa chỉ...', latitude, longitude })
    try {
      const location = await api.reverseGeocodeLocation(latitude, longitude)
      if (!location) { setLookupError('Không thể tìm địa chỉ của điểm này. Hãy chọn lại một vị trí gần đường hoặc địa điểm cụ thể.'); return }
      setPreviewLocation(location)
      setAddressLine(location.label)
    } catch {
      setLookupError('Dịch vụ bản đồ đang bận. Marker vẫn được giữ; hãy nhấp lại để lấy địa chỉ.');
    } finally { setResolving(false) }
  }
  const submit = async (event: React.FormEvent) => {
    event.preventDefault(); setSaving(true)
    try {
      const location = previewLocation ?? await resolveAddress()
      if (!location) { onError('Không thể lưu vì chưa xác định được vị trí trên bản đồ.'); return }
      await api.createProviderVenue({ name, addressLine: addressLine.trim(), district: location.district ?? location.city ?? 'Khu vực chưa xác định', city: location.city ?? 'Việt Nam', latitude: location.latitude, longitude: location.longitude }, token)
      onDone()
    } catch (e) { onError(e instanceof Error ? e.message : 'Không thể thêm địa điểm.') } finally { setSaving(false) }
  }
  const updateAddress = (value: string) => { setAddressLine(value); setPreviewLocation(null); setLookupError('') }
  return <form className="provider-form catalog-form venue-form" onSubmit={submit}><h3>Thêm địa điểm</h3><label>Tên địa điểm<input required minLength={2} list="venue-name-suggestions" value={name} onChange={(e) => setName(e.target.value)} placeholder="Ví dụ: Sân cầu lông ABC" /></label><label>Địa chỉ cụ thể<input required minLength={5} name="street-address" autoComplete="street-address" list="address-suggestions" value={addressLine} onChange={(e) => updateAddress(e.target.value)} placeholder="Hoặc chọn trực tiếp trên bản đồ" /></label><div className="venue-form-actions"><button type="button" disabled={resolving || saving} onClick={openMap} className="btn btn-outline-primary rounded-pill">{resolving ? 'Đang tìm vị trí...' : 'Chọn trên bản đồ'}</button><button disabled={saving || resolving} className="btn btn-primary rounded-pill">{saving ? 'Đang lưu...' : 'Lưu địa điểm'}</button></div><datalist id="venue-name-suggestions">{venueNameSuggestions.map((value) => <option value={value} key={value} />)}</datalist><datalist id="address-suggestions">{addressSuggestions.map((value) => <option value={value} key={value} />)}</datalist>{lookupError && <div className="venue-map-error">{lookupError}</div>}{isMapOpen && <VenueLocationPickerMap location={previewLocation} venueName={name || 'Địa điểm mới'} resolving={resolving} onPick={pickLocationFromMap} /> }<small>Nhấn “Chọn trên bản đồ”, sau đó nhấp vào vị trí mong muốn. OpenSlot sẽ tự điền địa chỉ cụ thể và tọa độ.</small></form>
}

function VenueMapClickHandler({ onPick }: { onPick: (latitude: number, longitude: number) => void }) {
  useMapEvents({ click: (event) => onPick(event.latlng.lat, event.latlng.lng) })
  return null
}

function VenueLocationPickerMap({ location, venueName, resolving, onPick }: { location: GeocodedLocation | null; venueName: string; resolving: boolean; onPick: (latitude: number, longitude: number) => void }) {
  const point = location ? [location.latitude, location.longitude] as [number, number] : null
  const center = point ?? [21.0285, 105.8542] as [number, number]
  return <section className="venue-map-preview"><div className="venue-map-heading"><div><b><i className="bi bi-geo-alt-fill" /> {resolving ? 'Đang xác định địa chỉ...' : point ? 'Vị trí đã chọn' : 'Nhấp vào bản đồ để chọn vị trí'}</b><span>{point ? location?.label : 'Kéo hoặc phóng to bản đồ, sau đó nhấp vào đúng vị trí địa điểm.'}</span></div><small>{point ? (location?.district ?? location?.city ?? 'Việt Nam') : 'Mặc định: Hà Nội'}</small></div><MapContainer key={point ? `${point[0]}-${point[1]}` : 'hanoi-picker'} center={center} zoom={point ? 16 : 13} scrollWheelZoom className="leaflet-map"><TileLayer attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" /><VenueMapClickHandler onPick={onPick} />{point && <CircleMarker center={point} radius={12} pathOptions={{ color: '#ffffff', weight: 3, fillColor: '#ee7158', fillOpacity: 1 }}><Popup><b>{venueName}</b><br />{location?.label}</Popup></CircleMarker>}</MapContainer></section>
}

function ResourceForm({ token, venues, onDone, onError }: { token: string; venues: ProviderVenue[]; onDone: () => void; onError: (message: string) => void }) {
  const [venueId, setVenueId] = useState(''); const [name, setName] = useState(''); const [resourceType, setResourceType] = useState(''); const [code, setCode] = useState(''); const [floorOrZone, setFloorOrZone] = useState(''); const [positionDescription, setPositionDescription] = useState(''); const [maxCapacity, setMaxCapacity] = useState('1'); const [saving, setSaving] = useState(false)
  const resourceTypes = ['Sân', 'Phòng', 'Bàn', 'Ghế', 'Khu vực', 'Máy / thiết bị']
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); try { await api.createProviderResource({ venueId, name, resourceType, code: code || null, floorOrZone: floorOrZone || null, positionDescription: positionDescription || null, maxCapacity: Number(maxCapacity) }, token); onDone() } catch (e) { onError(e instanceof Error ? e.message : 'Không thể thêm đơn vị đặt chỗ.') } finally { setSaving(false) } }
  return <form className="provider-form catalog-form" onSubmit={submit}><h3>Thêm đơn vị có thể đặt</h3><p className="form-hint">Ví dụ: sân số 2, bàn C-08, ghế gội số 3 hoặc phòng họp A. Đây là đơn vị khách thực sự nhận khi đặt slot.</p><label>Địa điểm<select required value={venueId} onChange={(e) => setVenueId(e.target.value)}><option value="">Chọn địa điểm</option>{venues.map((venue) => <option value={venue.id} key={venue.id}>{venue.name}</option>)}</select></label><label>Tên đơn vị<input required minLength={2} value={name} onChange={(e) => setName(e.target.value)} placeholder="Ví dụ: Sân số 2" /></label><label>Loại đơn vị<input required minLength={2} list="resource-type-suggestions" value={resourceType} onChange={(e) => setResourceType(e.target.value)} placeholder="Ví dụ: Sân cầu lông" /></label><label>Mã nhận diện<input maxLength={60} value={code} onChange={(e) => setCode(e.target.value)} placeholder="Ví dụ: S2 hoặc C-08" /></label><label>Tầng / khu vực<input maxLength={100} value={floorOrZone} onChange={(e) => setFloorOrZone(e.target.value)} placeholder="Ví dụ: Tầng 2, Khu A" /></label><label>Vị trí chi tiết<input maxLength={255} value={positionDescription} onChange={(e) => setPositionDescription(e.target.value)} placeholder="Ví dụ: Gần cửa sổ" /></label><label>Sức chứa tối đa<input required min="1" max="100" type="number" list="resource-capacity-suggestions" value={maxCapacity} onChange={(e) => setMaxCapacity(e.target.value)} /></label><datalist id="resource-type-suggestions">{resourceTypes.map((value) => <option value={value} key={value} />)}</datalist><datalist id="resource-capacity-suggestions">{capacitySuggestions.map((value) => <option value={value} key={value} />)}</datalist><button disabled={saving || !venues.length} className="btn btn-primary rounded-pill">{saving ? 'Đang lưu...' : 'Lưu đơn vị'}</button>{!venues.length && <small>Hãy tạo địa điểm trước.</small>}</form>
}

function ServiceForm({ token, venues, categories, onDone, onError }: { token: string; venues: ProviderVenue[]; categories: Category[]; onDone: () => void; onError: (message: string) => void }) {
  const [venueId, setVenueId] = useState(''); const [categoryId, setCategoryId] = useState(''); const [name, setName] = useState(''); const [description, setDescription] = useState(''); const [basePrice, setBasePrice] = useState(''); const submit = async (event: React.FormEvent) => { event.preventDefault(); try { await api.createProviderService({ venueId, categoryId: Number(categoryId), name, description, basePriceVnd: Number(basePrice), imageUrl: null }, token); onDone() } catch (e) { onError(e instanceof Error ? e.message : 'Không thể thêm dịch vụ.') } }
  return <form className="provider-form catalog-form" onSubmit={submit}><h3>Thêm dịch vụ</h3><p className="form-hint">Chỉ khai báo loại dịch vụ. Thời gian thực hiện sẽ được xác định riêng ở từng slot còn trống.</p><label>Địa điểm<select required value={venueId} onChange={(e) => setVenueId(e.target.value)}><option value="">Chọn địa điểm</option>{venues.map((venue) => <option value={venue.id} key={venue.id}>{venue.name}</option>)}</select></label><label>Danh mục<select required value={categoryId} onChange={(e) => setCategoryId(e.target.value)}><option value="">Chọn danh mục</option>{categories.map((category) => <option value={category.id} key={category.id}>{category.name}</option>)}</select></label><label>Tên dịch vụ<input required minLength={2} list="service-form-suggestions" value={name} onChange={(e) => setName(e.target.value)} /></label><label>Mô tả<input maxLength={2000} list="service-description-suggestions" value={description} onChange={(e) => setDescription(e.target.value)} /></label><label>Giá niêm yết tham khảo (VND)<input required type="number" min="1" list="service-price-suggestions" value={basePrice} onChange={(e) => setBasePrice(e.target.value)} /></label><datalist id="service-form-suggestions">{popularServiceSearches.map((value) => <option value={value} key={value} />)}</datalist><datalist id="service-description-suggestions">{descriptionSuggestions.map((value) => <option value={value} key={value} />)}</datalist><datalist id="service-price-suggestions">{priceSuggestions.map((value) => <option value={value} key={value} />)}</datalist><button disabled={!venues.length} className="btn btn-primary rounded-pill">Lưu dịch vụ</button>{!venues.length && <small>Hãy tạo địa điểm trước khi thêm dịch vụ.</small>}</form>
}

function CheckInPanel({ token }: { token: string }) { const [code, setCode] = useState(''); const [pin, setPin] = useState(''); const [message, setMessage] = useState(''); const checkIn = async (event: React.FormEvent) => { event.preventDefault(); try { await api.checkIn(code, pin, token); setMessage('Check-in thành công. Giữ mã để hoàn tất dịch vụ.') } catch (e) { setMessage(e instanceof Error ? e.message : 'Không thể check-in.') } }; const complete = async () => { if (!code) { setMessage('Nhập mã booking cần hoàn tất.'); return }; try { await api.completeBooking(code, token); setMessage('Dịch vụ đã được đánh dấu hoàn tất.'); setCode(''); setPin('') } catch (e) { setMessage(e instanceof Error ? e.message : 'Không thể hoàn tất booking.') } }; return <form onSubmit={checkIn} className="checkin-panel"><div><b><i className="bi bi-qr-code-scan" /> Check-in khách</b><span>Nhập mã OpenSlot và PIN của khách.</span></div><input required value={code} onChange={(e) => setCode(e.target.value.toUpperCase())} placeholder="OS-XXXXXXXX" /><input value={pin} onChange={(e) => setPin(e.target.value)} inputMode="numeric" placeholder="PIN 6 số" /><button className="btn btn-outline-primary rounded-pill">Check-in</button><button type="button" onClick={complete} className="btn btn-outline-success rounded-pill">Hoàn tất</button>{message && <small>{message}</small>}</form> }

function AdminPage({ session, mode }: { session: Session; mode: 'admin' | 'manager' }) {
  const [providers, setProviders] = useState<ProviderProfile[]>([])
  const [providerDetail, setProviderDetail] = useState<AdminProviderDetail | null>(null)
  const [detailLoading, setDetailLoading] = useState(false)
  const [users, setUsers] = useState<AdminUser[]>([])
  const [managedServices, setManagedServices] = useState<AdminService[]>([])
  const [managedSlots, setManagedSlots] = useState<AdminSlot[]>([])
  const [reports, setReports] = useState<Report[]>([])
  const [stats, setStats] = useState<AdminDashboard | null>(null)
  const [filter, setFilter] = useState<number | undefined>()
  const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(true); const isAdmin = mode === 'admin'
  // oxlint-disable-next-line react/set-state-in-effect -- loading belongs to the request lifecycle
  const refresh = () => { setLoading(true); Promise.all([api.adminProviders(session.accessToken, filter), api.adminDashboard(session.accessToken), api.reports(session.accessToken), api.adminUsers(session.accessToken), api.adminServices(session.accessToken), api.adminSlots(session.accessToken)]).then(([providerData, dashboardData, reportData, userData, serviceData, slotData]) => { setProviders(providerData); setStats(dashboardData); setReports(reportData); setUsers(userData); setManagedServices(serviceData); setManagedSlots(slotData) }).catch((e: Error) => setError(e.message)).finally(() => setLoading(false)) }
  useEffect(refresh, [session.accessToken, filter])
  const update = async (provider: ProviderProfile, action: 'approve' | 'suspend' | 'reject') => { try { if (action === 'approve') await api.approveProvider(provider.id, session.accessToken); else if (action === 'reject') await api.rejectProvider(provider.id, session.accessToken); else await api.suspendProvider(provider.id, session.accessToken); const actionText = action === 'approve' ? 'duyệt' : action === 'reject' ? 'yêu cầu bổ sung hồ sơ' : 'tạm khóa'; setMessage(`${provider.businessName} đã được ${actionText}.`); refresh() } catch (e) { setError(e instanceof Error ? e.message : 'Không thể cập nhật provider.') } }
  const resolve = async (report: Report) => { try { await api.resolveReport(report.id, 'Đã kiểm tra và xử lý bởi quản trị viên.', session.accessToken); setMessage('Báo cáo đã được xử lý.'); refresh() } catch (e) { setError(e instanceof Error ? e.message : 'Không thể xử lý báo cáo.') } }
  const toggleUser = async (user: AdminUser) => { try { if (user.isSuspended) await api.restoreUser(user.id, session.accessToken); else await api.suspendUser(user.id, session.accessToken); setMessage(`Đã ${user.isSuspended ? 'mở khóa' : 'tạm khóa'} tài khoản ${user.email}.`); refresh() } catch (e) { setError(e instanceof Error ? e.message : 'Không thể cập nhật tài khoản.') } }
  const toggleManager = async (user: AdminUser) => { try { const targetIsManager = user.roles.includes('Manager'); if (targetIsManager) await api.revokeManager(user.id, session.accessToken); else await api.grantManager(user.id, session.accessToken); setMessage(`Đã ${targetIsManager ? 'thu hồi' : 'cấp'} quyền Manager cho ${user.email}.`); refresh() } catch (e) { setError(e instanceof Error ? e.message : 'Không thể cập nhật quyền Manager.') } }
  const toggleService = async (service: AdminService) => { try { await api.setServiceActive(service.id, !service.isActive, session.accessToken); setMessage(`Đã ${service.isActive ? 'ẩn' : 'mở lại'} dịch vụ ${service.name}.`); refresh() } catch (e) { setError(e instanceof Error ? e.message : 'Không thể cập nhật dịch vụ.') } }
  const cancelSlot = async (slot: AdminSlot) => { if (!window.confirm(`Hủy slot ${slot.serviceName}?`)) return; try { await api.adminCancelSlot(slot.id, session.accessToken); setMessage('Slot đã được hủy.'); refresh() } catch (e) { setError(e instanceof Error ? e.message : 'Không thể hủy slot.') } }
  const viewProvider = async (provider: ProviderProfile) => { setError(''); setDetailLoading(true); try { setProviderDetail(await api.adminProviderDetail(provider.id, session.accessToken)) } catch (e) { setError(e instanceof Error ? e.message : 'Không thể tải chi tiết đối tác.') } finally { setDetailLoading(false) } }
  return <div className="container dashboard">
    <p className="eyebrow">{isAdmin ? 'Quản trị hệ thống' : 'Vận hành nền tảng'}</p><h1>{isAdmin ? 'Tổng quan OpenSlot' : 'Trung tâm vận hành'}</h1><p className="dashboard-copy">{isAdmin ? 'Quản lý toàn hệ thống, phân quyền Manager và theo dõi mọi hoạt động.' : 'Theo dõi vận hành, duyệt đối tác và xử lý vi phạm trên OpenSlot.'}</p>
    {stats && <div className="admin-stats admin-stats-wide"><div><span>Người dùng</span><b>{stats.users}</b></div><div><span>Slot đang mở</span><b>{stats.publishedSlots}</b></div><div><span>Booking</span><b>{stats.bookings}</b></div><div><span>Tỷ lệ lấp đầy</span><b>{stats.fillRatePercent}%</b></div><div><span>No-show</span><b>{stats.noShows}</b></div></div>}
    {error && <div className="alert alert-danger">{error}</div>}{message && <div className="alert alert-success">{message}</div>}
    <div className="admin-section-title"><h2>Quản lý đối tác</h2><div className="admin-filter"><button className={filter === undefined ? 'active' : ''} onClick={() => setFilter(undefined)}>Tất cả</button><button className={filter === 0 ? 'active' : ''} onClick={() => setFilter(0)}>Chờ duyệt</button><button className={filter === 1 ? 'active' : ''} onClick={() => setFilter(1)}>Đã duyệt</button><button className={filter === 3 ? 'active' : ''} onClick={() => setFilter(3)}>Cần bổ sung</button><button className={filter === 2 ? 'active' : ''} onClick={() => setFilter(2)}>Tạm khóa</button></div></div>
    {loading ? <div className="empty-state"><div className="spinner-border text-primary" /></div> : <>
      <div className="provider-table admin-table"><div className="table-head"><span>Doanh nghiệp</span><span>Người phụ trách</span><span>Trạng thái</span><span>Thao tác</span></div>{providers.map((provider) => <div className="table-row" key={provider.id}><span><button className="provider-detail-trigger" onClick={() => viewProvider(provider)}><b>{provider.businessName}</b><i className="bi bi-box-arrow-up-right" /></button><small>{provider.contactPhone} · {provider.description || 'Chưa có mô tả'}</small></span><span><b>{provider.ownerName}</b><small>{provider.ownerEmail}</small></span><span><span className={`status-pill provider-status status-${provider.status}`}>{provider.status === 0 ? 'Chờ duyệt' : provider.status === 1 ? 'Đã duyệt' : provider.status === 3 ? 'Cần bổ sung' : 'Tạm khóa'}</span></span><span className="admin-actions"><button className="btn btn-sm btn-outline-secondary" onClick={() => viewProvider(provider)}>Xem</button>{provider.status !== 1 && <button className="btn btn-sm btn-outline-success" onClick={() => update(provider, 'approve')}>{provider.status === 2 ? 'Mở lại' : 'Duyệt'}</button>}{provider.status === 0 && <button className="btn btn-sm btn-outline-warning" onClick={() => update(provider, 'reject')}>Yêu cầu bổ sung</button>}{provider.status === 1 && <button className="btn btn-sm btn-outline-danger" onClick={() => update(provider, 'suspend')}>Khóa</button>}</span></div>)}</div>
      {detailLoading && <div className="provider-detail-panel loading"><div className="spinner-border text-primary" /><span>Đang tải chi tiết đối tác...</span></div>}
      {providerDetail && <ProviderDetailPanel detail={providerDetail} onClose={() => setProviderDetail(null)} />}
      <div className="admin-section-title"><h2>{isAdmin ? 'Quản lý tài khoản và Manager' : 'Theo dõi tài khoản'}</h2><span className="section-note">{users.filter((x) => x.isSuspended).length} tài khoản đang khóa</span></div>
      <div className="provider-table user-table"><div className="table-head"><span>Tài khoản</span><span>Ngày tạo</span><span>Vi phạm</span><span>Thao tác</span></div>{users.map((user) => { const targetIsAdmin = user.roles.includes('Admin'); const targetIsManager = user.roles.includes('Manager'); const canModerate = user.id !== session.user.id && !targetIsAdmin && (isAdmin || !targetIsManager); const canChangeManager = isAdmin && user.id !== session.user.id && !targetIsAdmin && (targetIsManager || (user.roles.includes('Customer') && !user.roles.includes('Provider'))); return <div className="table-row" key={user.id}><span><b>{user.displayName}</b><small>{user.email} · {roleLabel(user.roles)}</small></span><span>{formatTime(user.createdAtUtc)}</span><span>{user.strikeCount} strike {user.isSuspended && <small className="text-danger">Tài khoản bị khóa</small>}</span><span className="admin-actions">{canModerate && <button onClick={() => toggleUser(user)} className={`btn btn-sm ${user.isSuspended ? 'btn-outline-success' : 'btn-outline-danger'}`}>{user.isSuspended ? 'Mở khóa' : 'Tạm khóa'}</button>}{canChangeManager && <button onClick={() => toggleManager(user)} className={`btn btn-sm ${targetIsManager ? 'btn-outline-secondary' : 'btn-outline-primary'}`}>{targetIsManager ? 'Thu hồi Manager' : 'Cấp Manager'}</button>}{!canModerate && !canChangeManager && <span className="section-note">{targetIsAdmin ? 'Tài khoản Admin' : user.id === session.user.id ? 'Tài khoản hiện tại' : 'Chỉ có thể theo dõi'}</span>}</span></div>})}</div>
      <CategoryManagementPanel token={session.accessToken} />
      <div className="admin-section-title"><h2>Kiểm duyệt dịch vụ</h2><span className="section-note">{managedServices.filter((x) => !x.isActive).length} dịch vụ đang ẩn</span></div>
      <div className="provider-table service-table"><div className="table-head"><span>Dịch vụ</span><span>Đối tác</span><span>Giá gốc</span><span>Thao tác</span></div>{managedServices.map((service) => <div className="table-row" key={service.id}><span><b>{service.name}</b><small>{service.categoryName} · {service.venueName}</small></span><span>{service.providerName}</span><span>{formatMoney(service.basePriceVnd)}</span><span><button onClick={() => toggleService(service)} className={`btn btn-sm ${service.isActive ? 'btn-outline-danger' : 'btn-outline-success'}`}>{service.isActive ? 'Ẩn' : 'Mở lại'}</button></span></div>)}</div>
      <div className="admin-section-title"><h2>Kiểm duyệt slot</h2><span className="section-note">Tối đa 200 slot gần nhất</span></div>
      <div className="provider-table slot-admin-table"><div className="table-head"><span>Slot</span><span>Đối tác</span><span>Đã đặt</span><span>Thao tác</span></div>{managedSlots.map((slot) => <div className="table-row" key={slot.id}><span><b>{slot.serviceName}</b><small>{slot.venueName} · {formatTime(slot.startAtUtc)}</small></span><span>{slot.providerName}</span><span>{slot.confirmedBookingCount}/{slot.capacity}</span><span>{slot.status < 3 ? <button disabled={slot.confirmedBookingCount > 0} onClick={() => cancelSlot(slot)} className="btn btn-sm btn-outline-danger">Hủy</button> : <span className="status-pill">Đã đóng</span>}</span></div>)}</div>
      <div className="admin-section-title report-title"><h2>Báo cáo vi phạm</h2><span>{reports.filter((x) => x.status === 0).length} báo cáo đang mở</span></div>
      <div className="report-list">{reports.length ? reports.map((report) => <article key={report.id}><div><b>{report.targetType} · {report.targetId}</b><small>{report.reporterName} ({report.reporterEmail}) · {formatTime(report.createdAtUtc)}</small><p>{report.reason}</p></div>{report.status === 0 ? <button className="btn btn-sm btn-outline-success" onClick={() => resolve(report)}>Đánh dấu đã xử lý</button> : <span className="status-pill">Đã xử lý</span>}</article>) : <div className="empty-state"><p>Chưa có báo cáo nào.</p></div>}</div>
    </>}
  </div>
}

function ProviderDetailPanel({ detail, onClose }: { detail: AdminProviderDetail; onClose: () => void }) {
  const slotStatus = (status: number) => status === 0 ? 'Nháp' : status === 1 ? 'Đang mở' : status === 2 ? 'Hết chỗ' : status === 3 ? 'Đã hủy' : 'Đã hết hạn'
  return <section className="provider-detail-panel" aria-live="polite"><div className="provider-detail-heading"><div><p className="eyebrow">Chi tiết đối tác</p><h2>{detail.businessName}</h2><p>{detail.ownerName} · {detail.ownerEmail} · {detail.contactPhone}</p></div><button className="btn btn-outline-secondary btn-sm" onClick={onClose}><i className="bi bi-x-lg" /> Đóng</button></div>{detail.description && <p className="provider-detail-description">{detail.description}</p>}<div className="detail-stat-grid"><article><small>Địa điểm</small><b>{detail.summary.venueCount}</b></article><article><small>Đơn vị đặt chỗ</small><b>{detail.summary.resourceCount}</b></article><article><small>Dịch vụ</small><b>{detail.summary.serviceCount}</b></article><article><small>Slot đang mở</small><b>{detail.summary.publishedSlotCount}</b></article><article><small>Lượt đã đặt</small><b>{detail.summary.bookingCount}</b></article></div><div className="detail-section"><h3>Địa điểm và đơn vị nhận đặt chỗ</h3>{detail.venues.length ? <div className="detail-venue-grid">{detail.venues.map((venue) => <article key={venue.id}><b><i className="bi bi-geo-alt" /> {venue.name}</b><span>{venue.addressLine}, {venue.district}, {venue.city}</span>{venue.resources.length ? <ul>{venue.resources.map((resource) => <li key={resource.id}><strong>{resource.name}</strong>{resource.code && ` · ${resource.code}`}{resource.floorOrZone && ` · ${resource.floorOrZone}`}<small>{resource.resourceType}{resource.positionDescription ? ` · ${resource.positionDescription}` : ''} · tối đa {resource.maxCapacity} chỗ</small></li>)}</ul> : <em>Chưa khai báo đơn vị đặt chỗ.</em>}</article>)}</div> : <p className="section-note">Đối tác chưa có địa điểm.</p>}</div><div className="detail-section"><h3>Dịch vụ đang khai báo</h3>{detail.services.length ? <div className="detail-list">{detail.services.map((service) => <article key={service.id}><div><b>{service.name}</b><span>{service.categoryName} · {service.venueName}</span></div><strong>{formatMoney(service.basePriceVnd)}</strong><span className={`status-pill ${service.isActive ? '' : 'provider-status status-2'}`}>{service.isActive ? 'Đang hoạt động' : 'Đang ẩn'}</span></article>)}</div> : <p className="section-note">Chưa có dịch vụ.</p>}</div><div className="detail-section"><h3>30 slot gần nhất</h3>{detail.slots.length ? <div className="detail-list">{detail.slots.map((slot) => <article key={slot.id}><div><b>{slot.serviceName}</b><span>{slot.venueName}{slot.resourceName ? ` · ${slot.resourceName}${slot.resourceCode ? ` (${slot.resourceCode})` : ''}` : ''} · {formatSlotWindow(slot.startAtUtc, slot.endAtUtc)}</span></div><strong>{formatMoney(slot.dealPriceVnd)}</strong><span className="status-pill">{slotStatus(slot.status)} · {slot.confirmedBookingCount}/{slot.capacity}</span></article>)}</div> : <p className="section-note">Chưa có slot nào.</p>}</div></section>
}

function CategoryManagementPanel({ token }: { token: string }) {
  const [categories, setCategories] = useState<AdminCategory[]>([]); const [name, setName] = useState(''); const [iconName, setIconName] = useState('tag'); const [error, setError] = useState(''); const [message, setMessage] = useState('')
  const refresh = () => { api.adminCategories(token).then(setCategories).catch((e: Error) => setError(e.message)) }
  useEffect(refresh, [token])
  const create = async (event: React.FormEvent) => { event.preventDefault(); setError(''); try { await api.createAdminCategory({ name, iconName }, token); setName(''); setIconName('tag'); setMessage('Đã tạo danh mục để Provider lựa chọn khi đăng dịch vụ.'); refresh() } catch (e) { setError(e instanceof Error ? e.message : 'Không thể tạo danh mục.') } }
  const toggle = async (category: AdminCategory) => { try { await api.setAdminCategoryActive(category.id, !category.isActive, token); setMessage(`Đã ${category.isActive ? 'tạm ngưng' : 'mở lại'} danh mục ${category.name}.`); refresh() } catch (e) { setError(e instanceof Error ? e.message : 'Không thể cập nhật danh mục.') } }
  const icons = ['tag', 'trophy', 'sparkles', 'laptop', 'camera', 'joystick', 'tools', 'cup-hot', 'heart-pulse']
  return <section className="catalog-panel manager-catalog"><div className="admin-section-title"><div><p className="eyebrow">Danh mục toàn nền tảng</p><h2>Nhóm dịch vụ do Manager quản lý</h2></div><span className="section-note">Provider tự tạo dịch vụ cụ thể và chọn một danh mục phù hợp.</span></div><form onSubmit={create} className="provider-form catalog-form"><h3>Tạo danh mục mới</h3><label>Tên danh mục<input required minLength={2} maxLength={80} value={name} onChange={(e) => setName(e.target.value)} placeholder="Ví dụ: Ăn uống" /></label><label>Biểu tượng<select value={iconName} onChange={(e) => setIconName(e.target.value)}>{icons.map((icon) => <option value={icon} key={icon}>{icon}</option>)}</select></label><button className="btn btn-primary rounded-pill">Thêm danh mục</button></form>{error && <div className="alert alert-danger mt-3">{error}</div>}{message && <div className="alert alert-success mt-3">{message}</div>}<div className="resource-list">{categories.map((category) => <article className={!category.isActive ? 'inactive' : ''} key={category.id}><div><b><i className={`bi bi-${category.iconName}`} /> {category.name}</b><span>{category.slug} · {category.serviceCount} dịch vụ đang phân loại</span></div><button onClick={() => toggle(category)} className={`btn btn-sm ${category.isActive ? 'btn-outline-danger' : 'btn-outline-success'}`}>{category.isActive ? 'Tạm ngưng' : 'Mở lại'}</button></article>)}</div></section>
}

function NotificationsPage({ session }: { session: Session }) {
  const [items, setItems] = useState<Notification[]>([]); const [error, setError] = useState(''); const [loading, setLoading] = useState(true)
  // oxlint-disable-next-line react/set-state-in-effect -- loading belongs to the request lifecycle
  const refresh = () => { setLoading(true); api.notifications(session.accessToken).then(setItems).catch((e: Error) => setError(e.message)).finally(() => setLoading(false)) }
  useEffect(refresh, [session.accessToken])
  const read = async (item: Notification) => { if (!item.isRead) await api.readNotification(item.id, session.accessToken); if (item.link) window.location.assign(item.link); else refresh() }
  const readAll = async () => { await api.readAllNotifications(session.accessToken); refresh() }
  return <div className="container dashboard"><div className="provider-heading"><div><p className="eyebrow">Trung tâm cập nhật</p><h1>Thông báo</h1></div>{items.some((x) => !x.isRead) && <button className="btn btn-outline-primary rounded-pill" onClick={readAll}>Đánh dấu đã đọc</button>}</div>{error && <div className="alert alert-danger">{error}</div>}{loading ? <div className="empty-state"><div className="spinner-border text-primary" /></div> : <div className="notification-list">{items.length ? items.map((item) => <button onClick={() => read(item)} className={item.isRead ? 'read' : ''} key={item.id}><i className={`bi ${item.isRead ? 'bi-check-circle' : 'bi-bell-fill'}`} /><span><b>{item.title}</b><small>{item.message}</small><time>{formatTime(item.createdAtUtc)}</time></span></button>) : <div className="empty-state"><i className="bi bi-bell-slash" /><h3>Chưa có thông báo</h3></div>}</div>}</div>
}

function NotFoundPage() { return <div className="container confirmation-page"><div className="confirmation-card"><span className="success-mark not-found-mark"><i className="bi bi-signpost-split" /></span><p className="eyebrow">404 · Không tìm thấy</p><h1>Trang này không còn ở đây</h1><p>Đường dẫn có thể đã thay đổi hoặc slot không tồn tại.</p><NavLink to="/" className="btn btn-primary rounded-pill px-4">Về trang khám phá</NavLink></div></div> }

export default App
