import { useCallback, useEffect, useMemo, useState } from 'react'
import { CircleMarker, MapContainer, Popup, TileLayer } from 'react-leaflet'
import 'leaflet/dist/leaflet.css'
import { Navigate, NavLink, Route, Routes, useLocation, useNavigate, useParams } from 'react-router-dom'
import { QRCodeSVG } from 'qrcode.react'
import { api } from './api'
import type { AdminDashboard, AdminService, AdminSlot, AdminUser, Booking, BookingConfirmation, Category, DealSlot, MyProviderProfile, Notification, ProviderProfile, ProviderService, ProviderSlot, ProviderVenue, Report, Session } from './types'
import './App.css'

const sessionKey = 'openslot-session'
const formatMoney = (value: number) => new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND', maximumFractionDigits: 0 }).format(value)
const formatTime = (value: string) => new Intl.DateTimeFormat('vi-VN', { timeZone: 'Asia/Ho_Chi_Minh', weekday: 'short', day: '2-digit', month: '2-digit', hour: '2-digit', minute: '2-digit' }).format(new Date(value))
const roleLabel = (roles: string[]) => roles.includes('Provider') ? 'Đối tác' : roles.includes('Admin') ? 'Quản trị viên' : 'Khách hàng'

function getStoredSession(): Session | null { try { return JSON.parse(localStorage.getItem(sessionKey) ?? 'null') as Session | null } catch { return null } }

function App() {
  const [session, setSession] = useState<Session | null>(getStoredSession)
  const saveSession = (next: Session | null) => { setSession(next); if (next) localStorage.setItem(sessionKey, JSON.stringify(next)); else localStorage.removeItem(sessionKey) }
  return <>
    <header className="site-header">
      <NavLink to="/" className="brand"><span className="brand-mark"><i className="bi bi-lightning-charge-fill" /></span>Open<span>Slot</span></NavLink>
      <nav className="main-nav"><NavLink to="/" end>Khám phá</NavLink>{session && <NavLink to="/bookings">Lịch của tôi</NavLink>}{session?.user.roles.includes('Provider') && <NavLink to="/provider">Khu vực đối tác</NavLink>}{session?.user.roles.includes('Admin') && <NavLink to="/admin">Quản trị</NavLink>}</nav>
      <div className="user-actions">{session ? <><NavLink to="/notifications" className="notification-link" aria-label="Thông báo"><i className="bi bi-bell" /></NavLink><span className="user-label"><b>{session.user.displayName}</b><small>{roleLabel(session.user.roles)}</small></span><button className="btn btn-link text-decoration-none" onClick={() => saveSession(null)}>Đăng xuất</button></> : <><NavLink className="btn btn-link text-decoration-none" to="/login">Đăng nhập</NavLink><NavLink className="btn btn-primary rounded-pill px-4" to="/register">Tạo tài khoản</NavLink></>}</div>
    </header>
    <main><Routes>
      <Route path="/" element={<ExplorePage />} />
      <Route path="/slots/:slotId" element={<SlotDetailPage session={session} />} />
      <Route path="/login" element={<AuthPage mode="login" onAuthenticated={saveSession} />} />
      <Route path="/register" element={<AuthPage mode="register" onAuthenticated={saveSession} />} />
      <Route path="/bookings" element={session ? <BookingsPage session={session} /> : <Navigate to="/login" replace />} />
      <Route path="/provider" element={session?.user.roles.includes('Provider') ? <ProviderPage session={session} /> : <Navigate to="/" replace />} />
      <Route path="/admin" element={session?.user.roles.includes('Admin') ? <AdminPage session={session} /> : <Navigate to="/" replace />} />
      <Route path="/notifications" element={session ? <NotificationsPage session={session} /> : <Navigate to="/login" replace />} />
      <Route path="*" element={<NotFoundPage />} />
    </Routes></main>
    <footer><div><b>OpenSlot</b><span>Săn thời điểm trống. Tận hưởng giá hợp lý.</span></div><small>Demo đồ án cá nhân · ASP.NET Core + React</small></footer>
  </>
}

function ExplorePage() {
  const [categories, setCategories] = useState<Category[]>([]); const [slots, setSlots] = useState<DealSlot[]>([])
  const [activeCategory, setActiveCategory] = useState(''); const [district, setDistrict] = useState(''); const [keyword, setKeyword] = useState(''); const [appliedKeyword, setAppliedKeyword] = useState(''); const [coords, setCoords] = useState<{ latitude: number; longitude: number } | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [mapMode, setMapMode] = useState(false)
  useEffect(() => { api.categories().then(setCategories).catch(() => setCategories([])) }, [])
  // oxlint-disable-next-line react/set-state-in-effect -- loading is part of this request lifecycle
  useEffect(() => { setLoading(true); setError(''); const params = new URLSearchParams(); if (activeCategory) params.set('category', activeCategory); if (district) params.set('district', district); if (appliedKeyword) params.set('q', appliedKeyword); if (coords) { params.set('latitude', String(coords.latitude)); params.set('longitude', String(coords.longitude)) }; const query = params.toString() ? `?${params}` : ''; api.slots(query).then(setSlots).catch((e: Error) => setError(e.message)).finally(() => setLoading(false)) }, [activeCategory, district, appliedKeyword, coords])
  const useMyLocation = () => { if (!navigator.geolocation) { setError('Trình duyệt không hỗ trợ định vị.'); return }; navigator.geolocation.getCurrentPosition((position) => { setCoords({ latitude: position.coords.latitude, longitude: position.coords.longitude }); setError('') }, () => setError('Không thể lấy vị trí. Hãy cho phép quyền vị trí trong trình duyệt.')) }
  const search = (event: React.FormEvent) => { event.preventDefault(); setAppliedKeyword(keyword.trim()) }
  return <div className="explore-page">
    <section className="hero-section"><div className="container"><p className="eyebrow"><i className="bi bi-stars" /> Ưu đãi sát giờ, có giới hạn</p><h1>Chỗ trống hôm nay,<br /><em>giá tốt ngay lúc này.</em></h1><p className="hero-copy">OpenSlot kết nối các khung giờ còn trống từ đối tác với người dùng sẵn sàng trải nghiệm. Không chờ sale dài ngày, chỉ chọn đúng thời điểm.</p><form className="search-box" onSubmit={search}><div><i className="bi bi-search" /><input aria-label="Tìm dịch vụ" value={keyword} onChange={(e) => setKeyword(e.target.value)} placeholder="Tìm sân, salon, chỗ ngồi..." /></div><div><i className="bi bi-geo-alt" /><input aria-label="Khu vực" value={district} onChange={(e) => setDistrict(e.target.value)} placeholder="Khu vực, ví dụ: Thủ Đức" /></div><button type="button" className={`location-button ${coords ? 'active' : ''}`} onClick={useMyLocation} title="Sắp xếp theo khoảng cách"><i className="bi bi-crosshair" /></button><button className="btn btn-primary rounded-pill">Khám phá ngay <i className="bi bi-arrow-right" /></button></form></div></section>
    <section className="container content-section"><div className="category-row"><button className={!activeCategory ? 'category active' : 'category'} onClick={() => setActiveCategory('')}><i className="bi bi-grid" />Tất cả</button>{categories.map((item) => <button key={item.id} className={activeCategory === item.slug ? 'category active' : 'category'} onClick={() => setActiveCategory(item.slug)}><i className={`bi ${item.icon || 'bi-tag'}`} />{item.name}</button>)}</div><div className="section-heading"><div><p className="eyebrow">Sắp diễn ra</p><h2>Slot đáng săn gần bạn</h2></div><button className="view-toggle" onClick={() => setMapMode(!mapMode)}><i className={`bi bi-${mapMode ? 'list-ul' : 'map'}`} /> {mapMode ? 'Xem danh sách' : 'Xem trên bản đồ'}</button></div>{error && <div className="alert alert-danger">{error}</div>}{loading ? <div className="empty-state"><div className="spinner-border text-primary" /><p>Đang tìm slot tốt nhất...</p></div> : mapMode ? <SlotMap slots={slots} /> : <SlotGrid slots={slots} />}</section>
    <section className="how-it-works"><div className="container"><p className="eyebrow">Đơn giản, minh bạch</p><h2>Săn slot trong 3 bước</h2><div className="steps"><Step icon="bi-search-heart" number="01" title="Tìm đúng lúc" text="Lọc dịch vụ, địa điểm và giờ phù hợp với lịch của bạn." /><Step icon="bi-ticket-perforated" number="02" title="Giữ chỗ nhanh" text="Xác nhận slot trước khi hết chỗ; giá và điều kiện luôn rõ ràng." /><Step icon="bi-qr-code-scan" number="03" title="Check-in gọn" text="Dùng mã QR hoặc PIN tại địa điểm để bắt đầu trải nghiệm." /></div></div></section>
  </div>
}

function Step({ icon, number, title, text }: { icon: string; number: string; title: string; text: string }) { return <article className="step"><span>{number}</span><i className={`bi ${icon}`} /><h3>{title}</h3><p>{text}</p></article> }
function SlotGrid({ slots }: { slots: DealSlot[] }) { return <div className="slot-grid">{slots.length ? slots.map((slot) => <SlotCard key={slot.id} slot={slot} />) : <div className="empty-state full"><i className="bi bi-calendar-x" /><h3>Chưa có slot phù hợp</h3><p>Thử đổi danh mục hoặc khu vực tìm kiếm nhé.</p></div>}</div> }
function SlotCard({ slot }: { slot: DealSlot }) { const discount = Math.round((1 - slot.dealPriceVnd / slot.originalPriceVnd) * 100); return <NavLink to={`/slots/${slot.id}`} state={{ slot }} className="slot-card"><div className={`slot-visual visual-${slot.categorySlug}`}><span className="discount">-{discount}%</span><span className="spot-label"><i className="bi bi-lightning-fill" /> Còn {slot.remainingCapacity} chỗ</span><i className="bi bi-clock-history visual-icon" /></div><div className="slot-body"><div className="slot-meta"><span>{slot.categoryName}</span><span><i className="bi bi-geo-alt" /> {slot.distanceKm == null ? slot.district : `${slot.distanceKm} km`}</span></div><h3>{slot.serviceName}</h3><p className="venue"><i className="bi bi-building" /> {slot.venueName}</p><div className="time-row"><i className="bi bi-calendar-event" /> {formatTime(slot.startAtUtc)}</div><div className="price-row"><div><del>{formatMoney(slot.originalPriceVnd)}</del><strong>{formatMoney(slot.dealPriceVnd)}</strong></div><span className="arrow-circle"><i className="bi bi-arrow-up-right" /></span></div></div></NavLink> }

function SlotMap({ slots }: { slots: DealSlot[] }) { const center = useMemo<[number, number]>(() => slots.length ? [slots[0].latitude, slots[0].longitude] : [10.8231, 106.6297], [slots]); return <div className="map-canvas"><MapContainer center={center} zoom={13} scrollWheelZoom className="leaflet-map"><TileLayer attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" />{slots.map((slot) => <CircleMarker key={slot.id} center={[slot.latitude, slot.longitude]} radius={11} pathOptions={{ color: '#ffffff', weight: 3, fillColor: '#ee7158', fillOpacity: 1 }}><Popup><div className="map-info"><b>{slot.serviceName}</b><span>{formatMoney(slot.dealPriceVnd)} · còn {slot.remainingCapacity} chỗ</span></div></Popup></CircleMarker>)}</MapContainer></div> }

function SlotDetailPage({ session }: { session: Session | null }) {
  const { slotId } = useParams(); const navigate = useNavigate(); const location = useLocation(); const locationSlot = (location.state as { slot?: DealSlot } | null)?.slot; const [slot, setSlot] = useState<DealSlot | null>(locationSlot ?? null); const [status, setStatus] = useState<'idle' | 'loading'>('idle'); const [error, setError] = useState(''); const [confirmation, setConfirmation] = useState<BookingConfirmation | null>(null)
  useEffect(() => { if (!slotId || slot) return; api.slot(slotId).then(setSlot).catch((e: Error) => setError(e.message)) }, [slotId, slot])
  if (!slot) return <div className="container detail-shell"><div className="empty-state"><p>{error || 'Đang tải thông tin slot...'}</p></div></div>
  const book = async () => { if (!session) { navigate('/login'); return }; setStatus('loading'); setError(''); try { setConfirmation(await api.book(slot.id, session.accessToken)) } catch (e) { setError(e instanceof Error ? e.message : 'Không thể giữ chỗ.') } finally { setStatus('idle') } }
  const report = async () => { if (!session) { navigate('/login'); return }; const reason = window.prompt('Mô tả vấn đề bạn muốn báo cáo (tối thiểu 10 ký tự):'); if (!reason) return; try { await api.createReport('slot', slot.id, reason, session.accessToken); window.alert('Cảm ơn bạn. Báo cáo đã được gửi tới quản trị viên.') } catch (e) { setError(e instanceof Error ? e.message : 'Không thể gửi báo cáo.') } }
  if (confirmation) return <div className="container confirmation-page"><div className="confirmation-card"><span className="success-mark"><i className="bi bi-check-lg" /></span><p className="eyebrow">Giữ chỗ thành công</p><h1>Hẹn gặp bạn tại<br />{slot.venueName}!</h1><p>Đưa QR hoặc PIN bên dưới khi check-in. Bạn có thể xem lại trong “Lịch của tôi”.</p><div className="qr-wrap"><QRCodeSVG value={confirmation.qrPayload} size={180} /><strong>{confirmation.publicCode}</strong><span>PIN check-in: <b>{confirmation.checkInPin}</b></span></div><NavLink to="/bookings" className="btn btn-primary rounded-pill px-4">Xem lịch của tôi</NavLink></div></div>
  return <div className="container detail-shell"><NavLink to="/" className="back-link"><i className="bi bi-arrow-left" /> Quay lại khám phá</NavLink><div className="detail-grid"><section className="detail-main"><div className={`detail-visual visual-${slot.categorySlug}`}><span className="discount">-{Math.round((1 - slot.dealPriceVnd / slot.originalPriceVnd) * 100)}%</span><i className="bi bi-lightning-charge-fill" /></div><p className="eyebrow mt-4">{slot.categoryName}</p><h1>{slot.serviceName}</h1><p className="detail-venue"><i className="bi bi-building" /> {slot.venueName} · {slot.district}, {slot.city}</p><div className="detail-facts"><Fact icon="bi-calendar-event" label="Bắt đầu" value={formatTime(slot.startAtUtc)} /><Fact icon="bi-clock" label="Kết thúc" value={formatTime(slot.endAtUtc)} /><Fact icon="bi-geo-alt" label="Địa điểm" value={`${slot.district}, ${slot.city}`} /></div><article className="info-box"><h3><i className="bi bi-shield-check" /> Chính sách OpenSlot</h3><p>Giữ chỗ chỉ hợp lệ trước giờ bắt đầu ít nhất 15 phút. Hủy sát giờ hoặc không đến có thể được tính strike để bảo vệ đối tác và cộng đồng.</p></article><button onClick={report} className="report-button"><i className="bi bi-flag" /> Báo cáo thông tin không chính xác</button></section><aside className="booking-panel"><p>Giá ưu đãi sát giờ</p><div className="detail-price"><del>{formatMoney(slot.originalPriceVnd)}</del><strong>{formatMoney(slot.dealPriceVnd)}</strong></div><div className="seat-note"><i className="bi bi-people" /> Còn <b>{slot.remainingCapacity}/{slot.capacity}</b> chỗ khả dụng</div>{error && <div className="alert alert-danger py-2 small">{error}</div>}<button disabled={status === 'loading' || !slot.remainingCapacity} onClick={book} className="btn btn-primary w-100 rounded-pill py-3">{status === 'loading' ? 'Đang giữ chỗ...' : session ? 'Giữ chỗ ngay' : 'Đăng nhập để giữ chỗ'} <i className="bi bi-arrow-right" /></button><small className="d-block text-center mt-3">Không thanh toán online trong bản demo.</small></aside></div></div>
}
function Fact({ icon, label, value }: { icon: string; label: string; value: string }) { return <div><i className={`bi ${icon}`} /><span><small>{label}</small><b>{value}</b></span></div> }

function AuthPage({ mode, onAuthenticated }: { mode: 'login' | 'register'; onAuthenticated: (session: Session) => void }) {
  const navigate = useNavigate(); const [displayName, setDisplayName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false)
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setError(''); setLoading(true); try { const session = mode === 'login' ? await api.login(email, password) : await api.register(displayName, email, password); onAuthenticated(session); navigate('/') } catch (e) { setError(e instanceof Error ? e.message : 'Không thể tiếp tục.') } finally { setLoading(false) } }
  return <div className="auth-page"><section className="auth-pitch"><NavLink to="/" className="brand"><span className="brand-mark"><i className="bi bi-lightning-charge-fill" /></span>Open<span>Slot</span></NavLink><div><p className="eyebrow">Tận hưởng thông minh</p><h1>Khoảnh khắc trống<br />cũng đáng giá.</h1><p>Chọn dịch vụ đúng nơi, đúng thời điểm, đúng ngân sách.</p></div><div className="quote"><i className="bi bi-quote" /> Đừng để một khung giờ tốt bị bỏ trống.</div></section><section className="auth-form-wrap"><form onSubmit={submit} className="auth-form"><p className="eyebrow">{mode === 'login' ? 'Chào mừng trở lại' : 'Tạo tài khoản miễn phí'}</p><h1>{mode === 'login' ? 'Đăng nhập OpenSlot' : 'Bắt đầu săn slot'}</h1>{mode === 'register' && <label>Họ và tên<input required value={displayName} onChange={(e) => setDisplayName(e.target.value)} placeholder="Nguyễn Văn A" /></label>}<label>Email<input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="ban@email.com" /></label><label>Mật khẩu<input required minLength={8} type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Tối thiểu 8 ký tự" /></label>{error && <div className="alert alert-danger">{error}</div>}<button disabled={loading} className="btn btn-primary rounded-pill py-3">{loading ? 'Đang xử lý...' : mode === 'login' ? 'Đăng nhập' : 'Tạo tài khoản'} <i className="bi bi-arrow-right" /></button><p className="switch-auth">{mode === 'login' ? <>Chưa có tài khoản? <NavLink to="/register">Đăng ký</NavLink></> : <>Đã có tài khoản? <NavLink to="/login">Đăng nhập</NavLink></>}</p><div className="demo-login"><b>Demo nhanh</b><span>customer@openslot.local / Customer@12345</span></div></form></section></div>
}

function BookingsPage({ session }: { session: Session }) {
  const [bookings, setBookings] = useState<Booking[]>([]); const [error, setError] = useState(''); const [loading, setLoading] = useState(true)
  // oxlint-disable-next-line react/set-state-in-effect -- loading belongs to the request lifecycle
  const refresh = () => { setLoading(true); api.myBookings(session.accessToken).then(setBookings).catch((e: Error) => setError(e.message)).finally(() => setLoading(false)) }
  useEffect(refresh, [session.accessToken])
  const cancel = async (booking: Booking) => { if (!window.confirm(`Hủy booking ${booking.publicCode}?`)) return; try { await api.cancelBooking(booking.id, 'Người dùng hủy từ giao diện', session.accessToken); refresh() } catch (e) { setError(e instanceof Error ? e.message : 'Không thể hủy booking.') } }
  return <div className="container dashboard"><p className="eyebrow">Tài khoản của bạn</p><h1>Lịch trải nghiệm</h1><p className="dashboard-copy">Mã QR/check-in PIN được mở khi bạn giữ chỗ. Hãy đến đúng giờ để giữ lịch sử tốt.</p>{error && <div className="alert alert-danger">{error}</div>}{loading ? <div className="empty-state"><div className="spinner-border text-primary" /></div> : bookings.length ? <div className="booking-list">{bookings.map((booking) => <article className="booking-item" key={booking.id}><div className="booking-date"><b>{new Intl.DateTimeFormat('vi-VN', { day: '2-digit' }).format(new Date(booking.startAtUtc))}</b><span>thg {new Intl.DateTimeFormat('vi-VN', { month: '2-digit' }).format(new Date(booking.startAtUtc))}</span></div><div className="booking-info"><span className="status-pill">{booking.status === 0 ? 'Đã xác nhận' : booking.status === 3 ? 'Đã hủy' : 'Đã cập nhật'}</span><h3>{booking.serviceName}</h3><p><i className="bi bi-building" /> {booking.venueName} · <i className="bi bi-clock" /> {formatTime(booking.startAtUtc)}</p><b>{formatMoney(booking.dealPriceVnd)}</b></div><div className="booking-actions"><code>{booking.publicCode}</code>{booking.status === 0 && <button onClick={() => cancel(booking)} className="btn btn-outline-danger btn-sm rounded-pill">Hủy chỗ</button>}</div></article>)}</div> : <div className="empty-state"><i className="bi bi-calendar-heart" /><h3>Chưa có lịch nào</h3><NavLink className="btn btn-primary rounded-pill" to="/">Khám phá slot ngay</NavLink></div>}</div>
}

function ProviderPage({ session }: { session: Session }) {
  const [slots, setSlots] = useState<ProviderSlot[]>([]); const [services, setServices] = useState<ProviderService[]>([]); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [loading, setLoading] = useState(true); const [showForm, setShowForm] = useState(false)
  // oxlint-disable-next-line react/set-state-in-effect -- loading belongs to the request lifecycle
  const refresh = () => { setLoading(true); Promise.all([api.providerSlots(session.accessToken), api.providerServices(session.accessToken)]).then(([slotData, serviceData]) => { setSlots(slotData); setServices(serviceData) }).catch((e: Error) => setError(e.message)).finally(() => setLoading(false)) }
  useEffect(refresh, [session.accessToken])
  const publish = async (id: string) => { try { await api.publishProviderSlot(id, session.accessToken); setNotice('Slot đã được phát hành.'); refresh() } catch (e) { setError(e instanceof Error ? e.message : 'Không thể phát hành slot.') } }
  return <div className="container dashboard"><p className="eyebrow">Khu vực đối tác</p><div className="provider-heading"><div><h1>Quản lý slot trống</h1><p className="dashboard-copy">Tạo và công khai ưu đãi theo khung giờ còn trống của bạn.</p></div><button onClick={() => setShowForm(!showForm)} className="btn btn-primary rounded-pill"><i className="bi bi-plus-lg" /> {showForm ? 'Đóng form' : 'Tạo slot'}</button></div>{showForm && <ProviderSlotForm services={services} token={session.accessToken} onDone={() => { setShowForm(false); setNotice('Đã tạo slot nháp. Hãy phát hành khi sẵn sàng.'); refresh() }} onError={setError} />}{error && <div className="alert alert-danger">{error}</div>}{notice && <div className="alert alert-success">{notice}</div>}{loading ? <div className="empty-state"><div className="spinner-border text-primary" /></div> : <><div className="provider-table"><div className="table-head"><span>Dịch vụ</span><span>Thời gian</span><span>Giá deal</span><span>Chỗ còn</span></div>{slots.map((slot) => <div className="table-row" key={slot.id}><span><b>{slot.serviceName}</b><small>{slot.venueName}</small></span><span>{formatTime(slot.startAtUtc)}</span><span><b>{formatMoney(slot.dealPriceVnd)}</b></span><span>{Math.max(0, slot.capacity - slot.confirmedBookingCount)}/{slot.capacity} {slot.status === 0 && <button onClick={() => publish(slot.id)} className="btn btn-sm btn-outline-primary ms-2">Phát hành</button>}</span></div>)}</div><CheckInPanel token={session.accessToken} /><ProviderCatalogPanel token={session.accessToken} onServicesChanged={refresh} /></>}</div>
}

function ProviderSlotForm({ services, token, onDone, onError }: { services: ProviderService[]; token: string; onDone: () => void; onError: (message: string) => void }) {
  const [serviceId, setServiceId] = useState(''); const [start, setStart] = useState(''); const [originalPrice, setOriginalPrice] = useState(''); const [dealPrice, setDealPrice] = useState(''); const [capacity, setCapacity] = useState('1'); const [saving, setSaving] = useState(false)
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!serviceId || !start) return; const startAt = new Date(start); const selected = services.find((x) => x.id === serviceId); const endAt = new Date(startAt.getTime() + (selected?.defaultDurationMinutes ?? 60) * 60000); const closesAt = new Date(startAt.getTime() - 15 * 60000); setSaving(true); try { await api.createProviderSlot({ serviceOfferingId: serviceId, startAtUtc: startAt.toISOString(), endAtUtc: endAt.toISOString(), bookingOpensAtUtc: new Date().toISOString(), bookingClosesAtUtc: closesAt.toISOString(), originalPriceVnd: Number(originalPrice), dealPriceVnd: Number(dealPrice), capacity: Number(capacity) }, token); onDone() } catch (e) { onError(e instanceof Error ? e.message : 'Không thể tạo slot.') } finally { setSaving(false) } }
  return <form onSubmit={submit} className="provider-form"><h3>Tạo slot nháp</h3><label>Dịch vụ<select required value={serviceId} onChange={(e) => setServiceId(e.target.value)}><option value="">Chọn dịch vụ</option>{services.map((service) => <option key={service.id} value={service.id}>{service.name} · {service.venueName}</option>)}</select></label><label>Giờ bắt đầu<input required type="datetime-local" value={start} onChange={(e) => setStart(e.target.value)} /></label><label>Giá gốc (VND)<input required min="1" type="number" value={originalPrice} onChange={(e) => setOriginalPrice(e.target.value)} /></label><label>Giá deal (VND)<input required min="1" type="number" value={dealPrice} onChange={(e) => setDealPrice(e.target.value)} /></label><label>Số chỗ<input required min="1" max="100" type="number" value={capacity} onChange={(e) => setCapacity(e.target.value)} /></label><button disabled={saving || !services.length} className="btn btn-primary rounded-pill">{saving ? 'Đang tạo...' : 'Lưu slot nháp'}</button><small>Slot luôn đóng nhận đặt chỗ trước giờ bắt đầu tối thiểu 15 phút.</small></form>
}

function ProviderCatalogPanel({ token, onServicesChanged }: { token: string; onServicesChanged: () => void }) {
  const [profile, setProfile] = useState<MyProviderProfile | null>(null); const [venues, setVenues] = useState<ProviderVenue[]>([]); const [categories, setCategories] = useState<Category[]>([]); const [mode, setMode] = useState<'none' | 'profile' | 'venue' | 'service'>('none'); const [message, setMessage] = useState(''); const [error, setError] = useState('')
  const load = useCallback(() => Promise.all([api.providerProfile(token), api.providerVenues(token), api.categories()]).then(([profileData, venueData, categoryData]) => { setProfile(profileData); setVenues(venueData); setCategories(categoryData) }).catch((e: Error) => setError(e.message)), [token])
  useEffect(() => { load() }, [load])
  const success = (text: string) => { setMode('none'); setError(''); setMessage(text); load(); onServicesChanged() }
  return <section className="catalog-panel"><div className="admin-section-title"><div><p className="eyebrow">Thiết lập gian hàng</p><h2>Hồ sơ, địa điểm và dịch vụ</h2></div><div className="catalog-actions"><button onClick={() => setMode('profile')} className="btn btn-sm btn-outline-secondary">Sửa hồ sơ</button><button onClick={() => setMode('venue')} className="btn btn-sm btn-outline-secondary">Thêm địa điểm</button><button onClick={() => setMode('service')} className="btn btn-sm btn-outline-primary">Thêm dịch vụ</button></div></div>{error && <div className="alert alert-danger mt-3">{error}</div>}{message && <div className="alert alert-success mt-3">{message}</div>}<div className="catalog-summary"><article><small>Đối tác</small><b>{profile?.businessName ?? 'Đang tải...'}</b><span>{profile?.contactPhone}</span></article><article><small>Địa điểm</small><b>{venues.length}</b><span>{venues.map((x) => x.name).join(', ') || 'Chưa có địa điểm'}</span></article></div>{mode === 'profile' && profile && <ProviderProfileForm profile={profile} token={token} onDone={() => success('Đã cập nhật hồ sơ đối tác.')} onError={setError} />}{mode === 'venue' && <VenueForm token={token} onDone={() => success('Đã thêm địa điểm.')} onError={setError} />}{mode === 'service' && <ServiceForm token={token} venues={venues} categories={categories} onDone={() => success('Đã thêm dịch vụ.')} onError={setError} />}</section>
}

function ProviderProfileForm({ profile, token, onDone, onError }: { profile: MyProviderProfile; token: string; onDone: () => void; onError: (message: string) => void }) {
  const [businessName, setBusinessName] = useState(profile.businessName); const [contactPhone, setContactPhone] = useState(profile.contactPhone); const [description, setDescription] = useState(profile.description ?? ''); const submit = async (event: React.FormEvent) => { event.preventDefault(); try { await api.updateProviderProfile({ businessName, contactPhone, description }, token); onDone() } catch (e) { onError(e instanceof Error ? e.message : 'Không thể cập nhật hồ sơ.') } }
  return <form className="provider-form catalog-form" onSubmit={submit}><h3>Sửa hồ sơ đối tác</h3><label>Tên doanh nghiệp<input required minLength={2} maxLength={160} value={businessName} onChange={(e) => setBusinessName(e.target.value)} /></label><label>Số điện thoại<input required minLength={8} maxLength={30} value={contactPhone} onChange={(e) => setContactPhone(e.target.value)} /></label><label>Mô tả<input maxLength={2000} value={description} onChange={(e) => setDescription(e.target.value)} /></label><button className="btn btn-primary rounded-pill">Lưu hồ sơ</button></form>
}

function VenueForm({ token, onDone, onError }: { token: string; onDone: () => void; onError: (message: string) => void }) {
  const [name, setName] = useState(''); const [addressLine, setAddressLine] = useState(''); const [district, setDistrict] = useState(''); const [city, setCity] = useState('TP. Hồ Chí Minh'); const [latitude, setLatitude] = useState('10.8231'); const [longitude, setLongitude] = useState('106.6297'); const submit = async (event: React.FormEvent) => { event.preventDefault(); try { await api.createProviderVenue({ name, addressLine, district, city, latitude: Number(latitude), longitude: Number(longitude) }, token); onDone() } catch (e) { onError(e instanceof Error ? e.message : 'Không thể thêm địa điểm.') } }
  return <form className="provider-form catalog-form" onSubmit={submit}><h3>Thêm địa điểm</h3><label>Tên địa điểm<input required minLength={2} value={name} onChange={(e) => setName(e.target.value)} /></label><label>Địa chỉ<input required minLength={5} value={addressLine} onChange={(e) => setAddressLine(e.target.value)} /></label><label>Quận/huyện<input required value={district} onChange={(e) => setDistrict(e.target.value)} /></label><label>Thành phố<input required value={city} onChange={(e) => setCity(e.target.value)} /></label><label>Vĩ độ<input required type="number" step="any" min="-90" max="90" value={latitude} onChange={(e) => setLatitude(e.target.value)} /></label><label>Kinh độ<input required type="number" step="any" min="-180" max="180" value={longitude} onChange={(e) => setLongitude(e.target.value)} /></label><button className="btn btn-primary rounded-pill">Lưu địa điểm</button><small>Lấy tọa độ bằng cách nhấp chuột phải vào vị trí trên OpenStreetMap.</small></form>
}

function ServiceForm({ token, venues, categories, onDone, onError }: { token: string; venues: ProviderVenue[]; categories: Category[]; onDone: () => void; onError: (message: string) => void }) {
  const [venueId, setVenueId] = useState(''); const [categoryId, setCategoryId] = useState(''); const [name, setName] = useState(''); const [description, setDescription] = useState(''); const [duration, setDuration] = useState('60'); const [basePrice, setBasePrice] = useState(''); const submit = async (event: React.FormEvent) => { event.preventDefault(); try { await api.createProviderService({ venueId, categoryId: Number(categoryId), name, description, defaultDurationMinutes: Number(duration), basePriceVnd: Number(basePrice), imageUrl: null }, token); onDone() } catch (e) { onError(e instanceof Error ? e.message : 'Không thể thêm dịch vụ.') } }
  return <form className="provider-form catalog-form" onSubmit={submit}><h3>Thêm dịch vụ</h3><label>Địa điểm<select required value={venueId} onChange={(e) => setVenueId(e.target.value)}><option value="">Chọn địa điểm</option>{venues.map((venue) => <option value={venue.id} key={venue.id}>{venue.name}</option>)}</select></label><label>Danh mục<select required value={categoryId} onChange={(e) => setCategoryId(e.target.value)}><option value="">Chọn danh mục</option>{categories.map((category) => <option value={category.id} key={category.id}>{category.name}</option>)}</select></label><label>Tên dịch vụ<input required minLength={2} value={name} onChange={(e) => setName(e.target.value)} /></label><label>Mô tả<input maxLength={2000} value={description} onChange={(e) => setDescription(e.target.value)} /></label><label>Thời lượng (phút)<input required type="number" min="15" max="1440" value={duration} onChange={(e) => setDuration(e.target.value)} /></label><label>Giá gốc (VND)<input required type="number" min="1" value={basePrice} onChange={(e) => setBasePrice(e.target.value)} /></label><button disabled={!venues.length} className="btn btn-primary rounded-pill">Lưu dịch vụ</button>{!venues.length && <small>Hãy tạo địa điểm trước khi thêm dịch vụ.</small>}</form>
}

function CheckInPanel({ token }: { token: string }) { const [code, setCode] = useState(''); const [pin, setPin] = useState(''); const [message, setMessage] = useState(''); const checkIn = async (event: React.FormEvent) => { event.preventDefault(); try { await api.checkIn(code, pin, token); setMessage('Check-in thành công. Giữ mã để hoàn tất dịch vụ.') } catch (e) { setMessage(e instanceof Error ? e.message : 'Không thể check-in.') } }; const complete = async () => { if (!code) { setMessage('Nhập mã booking cần hoàn tất.'); return }; try { await api.completeBooking(code, token); setMessage('Dịch vụ đã được đánh dấu hoàn tất.'); setCode(''); setPin('') } catch (e) { setMessage(e instanceof Error ? e.message : 'Không thể hoàn tất booking.') } }; return <form onSubmit={checkIn} className="checkin-panel"><div><b><i className="bi bi-qr-code-scan" /> Check-in khách</b><span>Nhập mã OpenSlot và PIN của khách.</span></div><input required value={code} onChange={(e) => setCode(e.target.value.toUpperCase())} placeholder="OS-XXXXXXXX" /><input value={pin} onChange={(e) => setPin(e.target.value)} inputMode="numeric" placeholder="PIN 6 số" /><button className="btn btn-outline-primary rounded-pill">Check-in</button><button type="button" onClick={complete} className="btn btn-outline-success rounded-pill">Hoàn tất</button>{message && <small>{message}</small>}</form> }

function AdminPage({ session }: { session: Session }) {
  const [providers, setProviders] = useState<ProviderProfile[]>([])
  const [users, setUsers] = useState<AdminUser[]>([])
  const [managedServices, setManagedServices] = useState<AdminService[]>([])
  const [managedSlots, setManagedSlots] = useState<AdminSlot[]>([])
  const [reports, setReports] = useState<Report[]>([])
  const [stats, setStats] = useState<AdminDashboard | null>(null)
  const [filter, setFilter] = useState<number | undefined>()
  const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(true)
  // oxlint-disable-next-line react/set-state-in-effect -- loading belongs to the request lifecycle
  const refresh = () => { setLoading(true); Promise.all([api.adminProviders(session.accessToken, filter), api.adminDashboard(session.accessToken), api.reports(session.accessToken), api.adminUsers(session.accessToken), api.adminServices(session.accessToken), api.adminSlots(session.accessToken)]).then(([providerData, dashboardData, reportData, userData, serviceData, slotData]) => { setProviders(providerData); setStats(dashboardData); setReports(reportData); setUsers(userData); setManagedServices(serviceData); setManagedSlots(slotData) }).catch((e: Error) => setError(e.message)).finally(() => setLoading(false)) }
  useEffect(refresh, [session.accessToken, filter])
  const update = async (provider: ProviderProfile, action: 'approve' | 'suspend') => { try { if (action === 'approve') await api.approveProvider(provider.id, session.accessToken); else await api.suspendProvider(provider.id, session.accessToken); setMessage(`${provider.businessName} đã được ${action === 'approve' ? 'duyệt' : 'tạm khóa'}.`); refresh() } catch (e) { setError(e instanceof Error ? e.message : 'Không thể cập nhật provider.') } }
  const resolve = async (report: Report) => { try { await api.resolveReport(report.id, 'Đã kiểm tra và xử lý bởi quản trị viên.', session.accessToken); setMessage('Báo cáo đã được xử lý.'); refresh() } catch (e) { setError(e instanceof Error ? e.message : 'Không thể xử lý báo cáo.') } }
  const toggleUser = async (user: AdminUser) => { try { if (user.isSuspended) await api.restoreUser(user.id, session.accessToken); else await api.suspendUser(user.id, session.accessToken); setMessage(`Đã ${user.isSuspended ? 'mở khóa' : 'tạm khóa'} tài khoản ${user.email}.`); refresh() } catch (e) { setError(e instanceof Error ? e.message : 'Không thể cập nhật tài khoản.') } }
  const toggleService = async (service: AdminService) => { try { await api.setServiceActive(service.id, !service.isActive, session.accessToken); setMessage(`Đã ${service.isActive ? 'ẩn' : 'mở lại'} dịch vụ ${service.name}.`); refresh() } catch (e) { setError(e instanceof Error ? e.message : 'Không thể cập nhật dịch vụ.') } }
  const cancelSlot = async (slot: AdminSlot) => { if (!window.confirm(`Hủy slot ${slot.serviceName}?`)) return; try { await api.adminCancelSlot(slot.id, session.accessToken); setMessage('Slot đã được hủy.'); refresh() } catch (e) { setError(e instanceof Error ? e.message : 'Không thể hủy slot.') } }
  return <div className="container dashboard">
    <p className="eyebrow">Quản trị hệ thống</p><h1>Tổng quan OpenSlot</h1><p className="dashboard-copy">Theo dõi vận hành, duyệt đối tác và xử lý báo cáo vi phạm.</p>
    {stats && <div className="admin-stats admin-stats-wide"><div><span>Người dùng</span><b>{stats.users}</b></div><div><span>Slot đang mở</span><b>{stats.publishedSlots}</b></div><div><span>Booking</span><b>{stats.bookings}</b></div><div><span>Tỷ lệ lấp đầy</span><b>{stats.fillRatePercent}%</b></div><div><span>No-show</span><b>{stats.noShows}</b></div></div>}
    {error && <div className="alert alert-danger">{error}</div>}{message && <div className="alert alert-success">{message}</div>}
    <div className="admin-section-title"><h2>Quản lý đối tác</h2><div className="admin-filter"><button className={filter === undefined ? 'active' : ''} onClick={() => setFilter(undefined)}>Tất cả</button><button className={filter === 0 ? 'active' : ''} onClick={() => setFilter(0)}>Chờ duyệt</button><button className={filter === 1 ? 'active' : ''} onClick={() => setFilter(1)}>Đã duyệt</button><button className={filter === 2 ? 'active' : ''} onClick={() => setFilter(2)}>Tạm khóa</button></div></div>
    {loading ? <div className="empty-state"><div className="spinner-border text-primary" /></div> : <>
      <div className="provider-table admin-table"><div className="table-head"><span>Doanh nghiệp</span><span>Người phụ trách</span><span>Trạng thái</span><span>Thao tác</span></div>{providers.map((provider) => <div className="table-row" key={provider.id}><span><b>{provider.businessName}</b><small>{provider.contactPhone} · {provider.description || 'Chưa có mô tả'}</small></span><span><b>{provider.ownerName}</b><small>{provider.ownerEmail}</small></span><span><span className={`status-pill provider-status status-${provider.status}`}>{provider.status === 0 ? 'Chờ duyệt' : provider.status === 1 ? 'Đã duyệt' : 'Tạm khóa'}</span></span><span className="admin-actions">{provider.status !== 1 && <button className="btn btn-sm btn-outline-success" onClick={() => update(provider, 'approve')}>Duyệt</button>}{provider.status === 1 && <button className="btn btn-sm btn-outline-danger" onClick={() => update(provider, 'suspend')}>Khóa</button>}</span></div>)}</div>
      <div className="admin-section-title"><h2>Quản lý người dùng</h2><span className="section-note">{users.filter((x) => x.isSuspended).length} tài khoản đang khóa</span></div>
      <div className="provider-table user-table"><div className="table-head"><span>Tài khoản</span><span>Ngày tạo</span><span>Vi phạm</span><span>Thao tác</span></div>{users.map((user) => <div className="table-row" key={user.id}><span><b>{user.displayName}</b><small>{user.email}</small></span><span>{formatTime(user.createdAtUtc)}</span><span>{user.strikeCount} strike {user.isSuspended && <small className="text-danger">Tài khoản bị khóa</small>}</span><span><button onClick={() => toggleUser(user)} className={`btn btn-sm ${user.isSuspended ? 'btn-outline-success' : 'btn-outline-danger'}`}>{user.isSuspended ? 'Mở khóa' : 'Tạm khóa'}</button></span></div>)}</div>
      <div className="admin-section-title"><h2>Kiểm duyệt dịch vụ</h2><span className="section-note">{managedServices.filter((x) => !x.isActive).length} dịch vụ đang ẩn</span></div>
      <div className="provider-table service-table"><div className="table-head"><span>Dịch vụ</span><span>Đối tác</span><span>Giá gốc</span><span>Thao tác</span></div>{managedServices.map((service) => <div className="table-row" key={service.id}><span><b>{service.name}</b><small>{service.categoryName} · {service.venueName}</small></span><span>{service.providerName}</span><span>{formatMoney(service.basePriceVnd)}</span><span><button onClick={() => toggleService(service)} className={`btn btn-sm ${service.isActive ? 'btn-outline-danger' : 'btn-outline-success'}`}>{service.isActive ? 'Ẩn' : 'Mở lại'}</button></span></div>)}</div>
      <div className="admin-section-title"><h2>Kiểm duyệt slot</h2><span className="section-note">Tối đa 200 slot gần nhất</span></div>
      <div className="provider-table slot-admin-table"><div className="table-head"><span>Slot</span><span>Đối tác</span><span>Đã đặt</span><span>Thao tác</span></div>{managedSlots.map((slot) => <div className="table-row" key={slot.id}><span><b>{slot.serviceName}</b><small>{slot.venueName} · {formatTime(slot.startAtUtc)}</small></span><span>{slot.providerName}</span><span>{slot.confirmedBookingCount}/{slot.capacity}</span><span>{slot.status < 3 ? <button disabled={slot.confirmedBookingCount > 0} onClick={() => cancelSlot(slot)} className="btn btn-sm btn-outline-danger">Hủy</button> : <span className="status-pill">Đã đóng</span>}</span></div>)}</div>
      <div className="admin-section-title report-title"><h2>Báo cáo vi phạm</h2><span>{reports.filter((x) => x.status === 0).length} báo cáo đang mở</span></div>
      <div className="report-list">{reports.length ? reports.map((report) => <article key={report.id}><div><b>{report.targetType} · {report.targetId}</b><small>{report.reporterName} ({report.reporterEmail}) · {formatTime(report.createdAtUtc)}</small><p>{report.reason}</p></div>{report.status === 0 ? <button className="btn btn-sm btn-outline-success" onClick={() => resolve(report)}>Đánh dấu đã xử lý</button> : <span className="status-pill">Đã xử lý</span>}</article>) : <div className="empty-state"><p>Chưa có báo cáo nào.</p></div>}</div>
    </>}
  </div>
}

function NotificationsPage({ session }: { session: Session }) {
  const [items, setItems] = useState<Notification[]>([]); const [error, setError] = useState(''); const [loading, setLoading] = useState(true)
  // oxlint-disable-next-line react/set-state-in-effect -- loading belongs to the request lifecycle
  const refresh = () => { setLoading(true); api.notifications(session.accessToken).then(setItems).catch((e: Error) => setError(e.message)).finally(() => setLoading(false)) }
  useEffect(refresh, [session.accessToken])
  const read = async (item: Notification) => { if (!item.isRead) await api.readNotification(item.id, session.accessToken); if (item.link) window.location.assign(item.link); else refresh() }
  const readAll = async () => { await api.readAllNotifications(session.accessToken); refresh() }
  return <div className="container dashboard"><div className="provider-heading"><div><p className="eyebrow">Trung tâm cập nhật</p><h1>Thông báo</h1></div>{items.some((x) => !x.isRead) && <button className="btn btn-outline-primary rounded-pill" onClick={readAll}>Đánh dấu đã đọc</button>}</div>{error && <div className="alert alert-danger">{error}</div>}{loading ? <div className="empty-state"><div className="spinner-border text-primary" /></div> : <div className="notification-list">{items.length ? items.map((item) => <button onClick={() => read(item)} className={item.isRead ? 'read' : ''} key={item.id}><i className={`bi ${item.isRead ? 'bi-check-circle' : 'bi-bell-fill'}`} /><span><b>{item.title}</b><small>{item.message}</small><time>{formatTime(item.createdAtUtc)}</time></span></button>) : <div className="empty-state"><i className="bi bi-bell-slash" /><h3>Chưa có thông báo</h3></div>}</div>}</div>
}

function NotFoundPage() { return <div className="container confirmation-page"><div className="confirmation-card"><span className="success-mark not-found-mark"><i className="bi bi-signpost-split" /></span><p className="eyebrow">404 · Không tìm thấy</p><h1>Trang này không còn ở đây</h1><p>Đường dẫn có thể đã thay đổi hoặc slot không tồn tại.</p><NavLink to="/" className="btn btn-primary rounded-pill px-4">Về trang khám phá</NavLink></div></div> }

export default App
